certtools/intelmq

intelmq/bots/BOTS
intelmq/bots/experts/abusix/abusix.py
intelmq/bots/experts/abusix/lib.py

New expert bot leveraging Abusix (https://abusix.com/contactdb.html) to enrich the abuse contact from RIPE based. Resolving is done through DNS TXT query.

Expert abusix

---

intelmq/bots/parsers/torexitnode

New parser - torexitnode

---

README.md
docs/DevGuide.md
docs/FAQ.md
docs/UserGuide.md
intelmq/lib/message.py

This pull request does:
1. Adds docstrings to lib/bot.py
2. Relatively links documentation, so that someone who makes a fork has his documentation 
linked and not the official(and then maybe not working documentation).
3. Changes documentation files so that they have less long lines
4. Applied the pep8 command to lib/bot.py and adapted the results.

Cleaning up documentation

---

README.md

Adds a basic meta-guidelines list for guiding me and future developers
who come to the project. I hope it will help the development.

Add basic meta-guidelines for the project to README.md

---

.gitignore
scrips/vagrant/README.md
scrips/vagrant/Vagrantfile
scrips/vagrant/bootstrap.sh

Added Vagrant and bash provisioning script to create a ubuntu/trusty64 virtual machine with automated installation of IntelMQ v1.0-beta branch and IntelMQ-Manager.

Vagrant project for create Ubuntu VM and automatically install IntelMQ and IntelMQ Manager.

---

intelmq/bots/experts/cymru_whois/expert.py
intelmq/lib/harmonization.py

Quick fix to fix the bot in beta version

Fixup of cymru

---

intelmq/conf/harmonization.conf

Taxonomy beta fix

---

intelmq/lib/bot.py
intelmq/lib/cache.py
intelmq/lib/pipeline.py
intelmq/lib/utils.py

This PR does the following:
1. It adds docstrings to files in intelmq/lib/
2. It re-formats those files mostly according the output of the pep8 utility

Add docstrings to lib

---

intelmq/conf/harmonization.conf

Added missing parsers to the BOTS list

BOTS - URLVir parser

---

intelmq/bots/BOTS
intelmq/bots/outputs/restapi/output.py

Simple REST API output with persistent http session and possibility to use authentication tokens

REST API output bot

---

intelmq/bots/BOTS
intelmq/bots/parsers/turris/parser.py

Collector and Parser for Greylist data of Project Turris (CZ.NIC), for more information please see: https://www.turris.cz/en/greylist

Turris bot

---

intelmq/bots/collectors/http/collector_http.py
intelmq/bots/collectors/http/lib.py

default is Chrome, can be changed per bot in runtime parameters

http collector user agent

---

intelmq/bots/parsers/ci_army/parser.py
intelmq/bots/parsers/turris/parser.py

minor fixes to Turris and CI Army parsers (didn't work)

Parser fixes

---

intelmq/bots/BOTS
intelmq/bots/experts/reverse_dns/expert.py

add reverse_domain_name based on source/destination IP

Reverse DNS lookup expert bot

---

intelmq/bin/intelmqctl

The commit messages should be rather self-explaining:
* MAINT: PEP8 for intelmqctl
using autopep8
* ENH: Use new string formating instead of old % method
* ENH: use open() only in with-statement
* ENH: catch wrong user input and generalize log_bot
* If bot ID is not given or invalid, no exception will be thrown now
* The log_bot_* functions now have the positional argument first, then the optional parameter (e.g. bot id)
* Also, multiple (including named) arguments can now be used

Various minor changes/improvements in Intelmqctl

---

REQUIREMENTS
intelmq/bots/experts/abusix/expert.py
intelmq/bots/experts/abusix/lib.py
intelmq/bots/experts/asn_lookup/expert.py
intelmq/bots/experts/cymru_whois/expert.py
intelmq/bots/experts/cymru_whois/lib.py
intelmq/bots/experts/reverse_dns/expert.py
intelmq/bots/experts/ripencc_abuse_contact/expert.py
intelmq/bots/experts/ripencc_abuse_contact/lib.py
intelmq/bots/experts/taxonomy/expert.py
intelmq/bots/experts/tor_nodes/README
intelmq/bots/experts/tor_nodes/expert.py
intelmq/lib/bot.py
intelmq/lib/harmonization.py
intelmq/lib/test.py
intelmq/tests/bots/experts/abusix/test_expert.py
intelmq/tests/bots/experts/asn_lookup/README
intelmq/tests/bots/experts/asn_lookup/test_expert.py
intelmq/tests/bots/experts/cymru_whois/test_expert.py
intelmq/tests/bots/experts/reverse_dns/test_expert.py
intelmq/tests/bots/experts/ripencc_abuse_contact/test_expert.py
intelmq/tests/bots/experts/taxonomy/test_expert.py
intelmq/tests/bots/experts/tor_nodes/test_expert.py
intelmq/tests/bots/test_dummy_bot.py

Includes a fix for #297 
Of course all tests are passing :)

Tests for most experts

---

REQUIREMENTS
REQUIREMENTS3
intelmq/bots/outputs/restapi/output.py

- Request body encoding (better behavior with special characters) 
- More detailed logging (server response headers and body)

Rest API output tuning

---

docs/User-Guide.md
intelmq/bots/parsers/cleanmx/parser_phishing.py
intelmq/bots/parsers/cleanmx/parser_virus.py
intelmq/bots/parsers/dragonresearchgroup/parser_ssh.py
intelmq/bots/parsers/dragonresearchgroup/parser_vnc.py
intelmq/lib/bot.py
intelmq/lib/pipeline.py
intelmq/lib/utils.py
setup.py

* dragon research parsers: protocols added to events
* fix for #326, bot does not dump message
* remove zmq as required dependency
* fix for #338, additional values in csv
* DOC: meaning of REQUIREMENTS clarified
* DOC: intelmqdump in User-Guide
* utils/logger can skip stream logger

Fixes from last days

---

docs/Developers-Guide.md
docs/Harmonization-fields.md
docs/User-Guide.md
intelmq/bin/intelmqctl
intelmq/bin/intelmqdump
intelmq/bots/experts/deduplicator/expert.py
intelmq/lib/bot.py
intelmq/lib/harmonization.py
intelmq/lib/message.py
intelmq/lib/test.py
intelmq/tests/bots/experts/deduplicator/test_expert.py
intelmq/tests/bots/experts/reverse_dns/test_expert.py
intelmq/tests/bots/parsers/malwaredomainlist/test_parser.py
intelmq/tests/lib/test_harmonization.py
intelmq/tests/lib/test_message.py

* custom python environment as discussed in #343 
* Test for deduplicator bot
* intelmqdump detects empty files
* FQDN does not allow trailing dots as discussed in #369
* message.MessageFactory has new method `from_dict` to create message instance from dict (currently only conversion from json is implemented)
* small fixes

Bugfixes, custom python env, etc

---

docs/User-Guide.md

@aaronkaplan and @sebix if you have time, read it in order to check the English and if, in your perspective, the documentation fits the user needs. Thank you ;)

DOC: User Guide improvements

---

intelmq/bots/parsers/abusech/parser_domain.py
intelmq/bots/parsers/abusech/parser_ip.py
intelmq/tests/bots/parsers/abusech/test_parser_domain.py
intelmq/tests/bots/parsers/abusech/test_parser_ip.py

- added malware.name to both parsers
- created test for botha parsers
- fixed behaviour for empty messages (thank you tests)

added malware.name and test for abusech parsers

---

intelmq/bots/outputs/postgresql/output.py

Fixes (hopefully) github/certat#39

catch all relevant exceptions for restarting the connection to the DB.

---

intelmq/bots/outputs/postgresql/output.py
intelmq/bots/parsers/cymru_full_bogons/parser.py
intelmq/bots/parsers/dshield/parser_asn.py
intelmq/bots/parsers/dshield/parser_block.py
intelmq/bots/parsers/dshield/parser_domain.py
intelmq/bots/parsers/shadowserver/chargen_parser.py
intelmq/bots/parsers/shadowserver/drone_parser.py
intelmq/bots/parsers/shadowserver/microsoft_sinkhole_parser.py
intelmq/bots/parsers/shadowserver/qotd_parser.py
intelmq/bots/parsers/shadowserver/snmp_parser.py
intelmq/conf/harmonization.conf
intelmq/lib/bot.py
intelmq/lib/harmonization.py
intelmq/tests/bots/parsers/cymru_full_bogons/test_parser.py
intelmq/tests/bots/parsers/dshield/asdetailsascii.html
intelmq/tests/bots/parsers/dshield/block.txt
intelmq/tests/bots/parsers/dshield/suspiciousdomains_High.txt
intelmq/tests/bots/parsers/dshield/test_parser_asn.py
intelmq/tests/bots/parsers/dshield/test_parser_block.py
intelmq/tests/bots/parsers/dshield/test_parser_domain.py
intelmq/tests/lib/test_harmonization.py
intelmq/tests/lib/test_message.py

* dshield and cymru parser fixes (timezone, extra data) + tests
* JSON type in harmonization + tests
* tests for malware.name (changed with #413)

Parser fixes + tests

---

intelmq/bots/collectors/http/collector_http.py

Should there be a zip archive downloaded by the collector, unzip all files and create a report for each of them and log the unzipped file names.

collector-http autounzip

---

contrib/README.md
contrib/cron-jobs/maxmind
contrib/cron-jobs/pyasn

Added initial contrib cron job scripts.

---

intelmq/bots/BOTS
intelmq/bots/experts/url2fqdn/expert.py
intelmq/tests/bots/experts/url2fqdn/test_expert.py

expert bot to parse fqdn from the url and add it to the event

BOT: url2fqdn expert

---

intelmq/bots/outputs/redis/README.md

Just an explanation on the bot parameters and some usage examples.

Redis bot README.md file

---

intelmq/bots/experts/maxmind_geoip/README.md
intelmq/bots/outputs/postgresql/readme.md

This PR contains some small updates on the documentation of the maxmind_geoip expert bot and creates an initial documentation for the postgresql output bot.

Updated Documentation of geoip_expert and postgresql_output bot

---

docs/Developers-Guide.md
intelmq/bin/intelmqctl.py
intelmq/bots/collectors/bitsight/collector.py
intelmq/lib/bot.py
intelmq/lib/pipeline.py

* Bots are re-initialized on SIGHUP now :)
* new method `shutdown` is available for bots for a graceful shutdown
* internal names are "private" now (leading __)
* updated docs

Bot class: renamings, reloading on sighup, shutdown method

---

intelmq/bots/collectors/mail/collector_mail_url.py

These changes attempt to make the mail URL collector bot more robust
and user friendly.

Make URL mail collector bot more robust

---

docs/User-Guide.md

Improved the writing at some random places.

User-Guide.md: some language improvements

---

intelmq/bots/BOTS
intelmq/bots/parsers/generic/parser_csv.py

new parameter for generic csv parser to skip the first row with csv headers

ENH: omit headers while csv parsing

---

intelmq/bots/BOTS
intelmq/bots/collectors/misp/collector.py

The 3rd parameter of the class is now a boolean to verify or not the
certificate proposed by the server.
Cosmetic changes: Remove unused imports and fix pep8.

The format of PyMISP changed, update accordingly.

---

intelmq/bots/collectors/misp/collector.py
intelmq/bots/parsers/misp/parser.py

* PyMISP now has helpers to add and remove tags, use them and remove extra code
* Avoid crash of the parser if the event has no tags.

Cleanup & use PyMISP

---

CHANGELOG.md
intelmq/bots/BOTS
intelmq/bots/collectors/rt/README.md
intelmq/bots/collectors/rt/REQUIREMENTS.txt
intelmq/bots/collectors/rt/collector_rt.py
intelmq/lib/message.py

Collects reports from a RTIR-instance and passes them other bots (parsers). Can also take events.
Used in our setup at cert.at

RTIR Collector

---

intelmq/etc/harmonization.conf

Address issue #584

---

intelmq/bots/experts/modify/examples/morefeeds.conf

I'm not crazy about the file name but here it goes. See also PR #575.

Modify bot: Add an additional example config

---

intelmq/etc/harmonization.conf
intelmq/lib/message.py

add the ignore case thing for regexps for the harmonisation

add re.IGNORECASE (iregex) support to the harmonisation.conf

---

setup.py

This should have been part of #589.

Install new modify bot example config file

---

config_files.py

Very simple script to rewrite the config files a the way the travis tests pass.

Add script to rewrite config files so travis is happy.

---

docs/Harmonization-fields.md
intelmq/bots/collectors/misp/collector.py
intelmq/bots/parsers/misp/parser.py
intelmq/etc/harmonization.conf
intelmq/tests/bots/parsers/misp/misp_event.json
intelmq/tests/bots/parsers/misp/test_parser.py

* First commit is a bugfix, feel free to just cherry-pick this one.
* Second commit is required for the 3rd one
* Third commit add a bunch of changes in the MISP bots, but I think they are relevant and useful for most of the intelMQ users.

Update misp module

---

docs/Harmonization-fields.md
intelmq/bin/intelmqctl.py
intelmq/bin/intelmqdump.py
intelmq/bots/experts/cymru_whois/expert.py
intelmq/bots/experts/cymru_whois/lib.py
intelmq/bots/parsers/autoshun/parser.py
intelmq/bots/parsers/misp/parser.py
intelmq/bots/parsers/shadowserver/parser.py
intelmq/etc/harmonization.conf
intelmq/lib/bot.py
intelmq/lib/harmonization.py
intelmq/lib/test.py
intelmq/tests/bots/experts/cymru_whois/test_expert.py
intelmq/tests/bots/parsers/shadowserver/chargen.csv
intelmq/tests/bots/parsers/shadowserver/chargen_short.csv
intelmq/tests/bots/parsers/shadowserver/test_chargen.py
intelmq/tests/bots/test_dummy_bot.py
intelmq/tests/lib/test_harmonization.py
intelmq/tests/lib/test_message.py

@dmth @swilde Please review the shadowserver part. (except `recover_line`, it will be rewritten by #618)
Fixes #478 #576 #587 #590 #594 #597 #599 #600 #603 #607 (x2)

A bunch of (bug)fixes

---

intelmq/bots/experts/cymru_whois/lib.py
intelmq/tests/bots/experts/cymru_whois/test_expert.py

fixes certtools/intelmq#635
Signed-off-by: Sebastian Wagner <sebix@sebix.at>

BUG: cymru lookup: handle no result for asn

---

intelmq/bin/intelmqctl.py

Currently it's not possible, as the name is rejected by the tool.

Ctl: allow clearing internal-queues

---

debian/conffiles
docs/User-Guide.md
intelmq/bin/intelmqctl.py
intelmq/etc/defaults.conf
intelmq/etc/system.conf
intelmq/lib/bot.py
intelmq/lib/test.py
intelmq/tests/lib/test_bot.py
intelmq/tests/test_conf.py
setup.py

system.conf is still read if the file exists, but a warning is emitted.
Related to #267

Deprecate system.conf

---

intelmq/bots/BOTS
intelmq/bots/experts/certat_contact_intern/expert.py
intelmq/bots/experts/contact_db_lookup/expert.py
intelmq/tests/bots/experts/certat_contact_intern/test_expert.py
intelmq/tests/bots/experts/contact_db_lookup/test_expert.py

Code is from certat repo and already tested in our setup
Addresses #665

Generic contact database lookup

---

intelmq/bin/intelmqctl.py
intelmq/lib/bot.py

Adds missing white space. And more pep8 compatible.

minor: fixes typo in deprecation msg.

---

.travis.yml
intelmq/bin/intelmq_psql_initdb.py
intelmq/tests/bin/test_psql_initdb.py

Basically only cherry-picking from our certat-branch.

Activate Postgres checks

---

CHANGELOG.md
intelmq/lib/harmonization.py
intelmq/tests/lib/test_harmonization.py

FQDNs only in IDN format

---

docs/Feeds.md
intelmq/bots/BOTS
intelmq/bots/parsers/abusech/parser_ransomware.py
intelmq/tests/bots/parsers/abusech/ransomwaretracker.csv
intelmq/tests/bots/parsers/abusech/test_parser_ransomware.py

Added the needed parser for Ransomware Tracker available from Abuse.ch.

Abuse.ch Ransomware Tracker

---

docs/Feeds.md
intelmq/bots/BOTS
intelmq/bots/parsers/bitcash/parser.py
intelmq/tests/bots/parsers/bitcash/blacklist
intelmq/tests/bots/parsers/bitcash/test_parser.py

Bit Cash parser for SYNchroACK's list in issue #384.

Bit Cash parser 

---

docs/images/Logo_Intel_MQ.svg

This logo was retrace by Seamus from the existing PNG's
the original logo and the author could not be acquired.
See intelmq-dev list for more information.

Added the logo of IntelMQ as SVG

---

intelmq/bots/experts/taxonomy/expert.py
intelmq/tests/bots/experts/taxonomy/test_expert.py

Be a bit clearer about the different cases on when to set which field

Make the taxonomy values lower case. Fixes #670

---

contrib/bash-completion/README.md
contrib/bash-completion/intelmq.sh
debian/intelmq.install
docs/User-Guide.md

It was so annoying now so I quickly coded some bash completion functions for ctl and dump
Please test it :)

Shell completion for executables in bin/

---

docs/Developers-Guide.md

* layout rules - relate to #799 
* document restructured

Developers-Guide Improvements

---

intelmq/bots/BOTS
intelmq/bots/collectors/xmpp/README.md
intelmq/bots/collectors/xmpp/collector.py
intelmq/bots/outputs/xmpp/README.md
intelmq/bots/outputs/xmpp/output.py

* Enhanced Collector to use Whitelists / Blacklists and only process messages of defined users
* Added Readme-Files

Added support for MUC in XMPP Output

---

intelmq/lib/bot.py
intelmq/tests/lib/test_parser_bot.py

fixes certtools/intelmq#779
The generic csv parser can now ignore lines starting with a defined list of characters to ignore comments.
Also, the message is stripped, so newlines at the beginning and the end are removed, which too poses problems onto the csv parser of python.

CSV parser: ignore empty lines and comments

---

intelmq/lib/bot.py
intelmq/lib/pipeline.py
intelmq/lib/utils.py

Fixes #612 
I successfully tested if for the disk space. For simulation of full memory, I manually triggered the resulting error in the library (I hope it works).

Handle Out of disk space/memory

---

intelmq/bots/parsers/spamhaus/parser_cert.py
intelmq/tests/bots/parsers/spamhaus/cert.txt
intelmq/tests/bots/parsers/spamhaus/test_parser_cert.py

Spamhaus cert: handle more invalid data

---

intelmq/bots/experts/gethostbyname/expert.py
intelmq/tests/bots/experts/gethostbyname/test_expert.py

Treat non existing records in GethostbynameExpert

---

CHANGELOG.md
docs/Harmonization-fields.md
intelmq/etc/harmonization.conf
intelmq/lib/bot.py
intelmq/lib/message.py
intelmq/tests/bin/initdb.sql
intelmq/tests/lib/test_collector_bot.py
intelmq/tests/lib/test_message.py

It's a string, not strictly an URL to give more freedom to the user
fixes certtools/intelmq#749
@sykaeh please also review (can't select you for the ticket)

Add feed.documentation

---

.travis.yml
intelmq/bin/intelmq_psql_initdb.py
intelmq/tests/bin/initdb.sql

fixes certtools/intelmq#728
ping @bernhard-herzog

Create indices in postgresql initialization

---

intelmq/bots/collectors/xmpp/collector.py
intelmq/bots/outputs/xmpp/output.py

https://github.com/certtools/intelmq/issues/879
More clear logging  messages. In addition the XMPP Bots stop, if a connection cannot be established.

ENH: logging in XMPP Bots

---

CHANGELOG.md
docs/Bots.md
intelmq/bots/experts/field_reducer/expert.py
intelmq/bots/experts/reducer/expert.py
intelmq/tests/bots/experts/field_reducer/test_expert.py
intelmq/tests/bots/experts/reducer/test_expert.py

This bot deletes fields from events, either using a whitelist or a blacklist.

New expert 'field reducer'

---

AUTHORS

Add AUTHORS file from the public git log infos. Fixes #888

---

CHANGELOG.md
NEWS.md
intelmq/bots/BOTS
intelmq/bots/experts/tor_nodes/expert.py
intelmq/tests/bots/experts/tor_nodes/test_expert.py

tor_nodes expert bot handle existing fields

---

intelmq/bots/parsers/alienvault/parser_otx.py

fix type in hash, 265 -> 256

---

intelmq/bots/parsers/spamhaus/parser_cert.py
intelmq/tests/bots/parsers/spamhaus/test_parser_cert.py

Strip API keys for spamhaus cert feed

---

README.rst
docs/INSTALL.md
docs/README.md
docs/UPGRADING.md
docs/User-Guide.md

Split and extend installation and upgrade doc

---

docs/Bots.md
intelmq/bots/BOTS
intelmq/bots/collectors/microsoft/REQUIREMENTS.txt
intelmq/bots/collectors/microsoft/collector_azure.py
intelmq/tests/bots/collectors/microsoft/test_collector_azure.py

Needed for MS DCU feed (feed description and configuration will follow)

Microsoft azure collector

---

intelmq/bin/intelmqdump.py

fixes certtools/intelmq#923
This is now displayed instead of the traceback:
Attention: This bot is not defined!
Restricted actions.
(q)uit, (d)elete file?

BUG: bin/dump: catch unconfigured bots

---

intelmq/bots/experts/abusix/lib.py
intelmq/bots/experts/cymru_whois/lib.py
intelmq/bots/experts/generic_db_lookup/expert.py
intelmq/bots/experts/ripencc_abuse_contact/expert.py
intelmq/bots/outputs/postgresql/output.py
intelmq/bots/outputs/redis/output.py
intelmq/bots/outputs/tcp/output.py
intelmq/bots/outputs/udp/output.py
intelmq/bots/parsers/shadowserver/parser.py
intelmq/lib/bot.py

Avoid bare excepts

---

docs/Data-Harmonization.md
docs/Harmonization-fields.md
intelmq/etc/harmonization.conf

* remove the unused reported identity
* remove the outdated data types section
* update the required fields section
* fix description of some destination fields

Harmonization documentation clarifications

---

intelmq/bots/parsers/shadowserver/config.py
intelmq/tests/bots/parsers/shadowserver/accessible_vnc.csv
intelmq/tests/bots/parsers/shadowserver/accessible_vnc_RECONSTRUCTED.csv
intelmq/tests/bots/parsers/shadowserver/test_accessible_vnc.py

As of today shadowserver delivers a new feed with accessible VNC servers

Shadowserver Accessible VNC parser

---

docs/User-Guide.md
intelmq/lib/bot.py
intelmq/lib/test.py
intelmq/tests/lib/test_bot.py
intelmq/tests/lib/test_parser_bot.py

Honor logging parameters in runtime

---

contrib/bash-completion/README.md

Modify the path to give exact path from base directory of git project.

Offer complete path to bash completion script

---

docs/Feeds.md

The cleanmx parser appears to be a single class now, detecting type based on URL args as of 87d5bea69.

Update for new CleanMX parser behaviour

---

docs/Developers-Guide.md

DOC: document branching mechanism

---

intelmq/bin/intelmqctl.py

catch permission errors in psutil

---

docs/User-Guide.md
intelmq/tests/bots/experts/cymru_whois/test_expert.py

Re-structured some sentences for more clarity

Lots of typo/grammar fixes.

---

CHANGELOG.md
NEWS.md
debian/changelog
docs/INSTALL.md
docs/User-Guide.md
intelmq/lib/test.py
intelmq/version.py

Scream now if I forgot something.
As soon as someone reviews this, I will push the tag and the packages.

Release 1.0 and update install docs

---

CHANGELOG.md
NEWS.md
debian/changelog
docs/INSTALL.md
docs/User-Guide.md
intelmq/bin/intelmqctl.py
intelmq/lib/test.py
intelmq/tests/bots/experts/ripencc_abuse_contact/test_expert.py

Cherry-picked everything from master which applies to develop (and resolved conflicts)

Merge master changes into develop

---

intelmq/lib/bot.py
intelmq/lib/test.py

lib/bot: log intelmq version

---

intelmq/bin/intelmqctl.py

fixes certtools/intelmq#1058
* checks syntax
* two required fields
* validity of regex if given

ctl: check harmonization conf

---

intelmq/bin/intelmqctl.py

JSON output fixes

---

CHANGELOG.md
intelmq/bin/intelmqctl.py

check commandline of running process for status

---

intelmq/bots/outputs/file/output.py

BUG: file output: close file on shutdown

---

CHANGELOG.md
intelmq/bots/BOTS
intelmq/bots/collectors/rt/README.md
intelmq/bots/collectors/rt/collector_rt.py

RT collector enhancements

---

intelmq/bin/intelmqctl.py

ENH: bin/ctl: simpler pid file check

---

intelmq/bots/parsers/shadowserver/config.py

Added support for new Shadowserver feed Accessible-Cisco-Smart-Install to parser config.

Added Shadowserver feed: Accessible-Cisco-Smart-Install

---

CHANGELOG.md
intelmq/bots/parsers/shadowserver/parser.py
intelmq/lib/test.py
intelmq/lib/utils.py
intelmq/tests/bots/experts/national_cert_contact_certat/test_expert.py
intelmq/tests/lib/test_bot.py
intelmq/tests/lib/test_parser_bot.py

lib/bot: capture warnings in bot class

---

contrib/elasticsearch/README.md
contrib/elasticsearch/elasticmapper

@aaronkaplan as we talked :+1: 
**Mapping Ouput:** [mapping.txt](https://github.com/certtools/intelmq/files/1608169/mapping.txt)

ElasticMapper Tool (contrib)

---

CHANGELOG.md
intelmq/bin/intelmqctl.py
intelmq/bots/collectors/alienvault_otx/collector.py
intelmq/bots/collectors/mail/collector_mail_attach.py
intelmq/bots/collectors/mail/collector_mail_url.py

It seems to me these log lines will suit to most test cases.

mail collectors: added debug information #1078

---

CHANGELOG.md
docs/Data-Harmonization.md
intelmq/lib/message.py
intelmq/tests/lib/test_message.py

BUG: enforce rule on harmonization key names

---

intelmq/bin/intelmqctl.py

fixes certtools/intelmq#1059
fixes certtools/intelmq#1082
checks if redis connection succeeds
and if there are more queues in redis than in the pipeline configuration

ENH: ctl: check redis and orphan queues

---

CHANGELOG.md
intelmq/bots/outputs/smtp/output.py

BUG: fix smtp output starttls

---

intelmq/bin/intelmqctl.py
intelmq/bin/intelmqdump.py
intelmq/bots/experts/filter/expert.py
intelmq/bots/parsers/anubisnetworks/parser.py
intelmq/lib/bot.py
intelmq/lib/bot_debugger.py
intelmq/lib/harmonization.py
intelmq/lib/message.py
intelmq/lib/utils.py
intelmq/tests/lib/test_message.py

Most notably: Implemented `Message.__eq__` for proper comparisons
See: https://lgtm.com/projects/g/certtools/intelmq
Many of them are false positives, but some hints are very good :)

ENH: Fix issues found by lgtm tool

---

.travis.yml
CHANGELOG.md
docs/Bots.md
docs/Feeds.md
intelmq/bots/BOTS
intelmq/bots/collectors/http/collector_http.py
intelmq/tests/bots/collectors/http/test_collector.py

Allows having the time/date in the URL

HTTP collector: URL formatting

---

CHANGELOG.md
intelmq/lib/harmonization.py
intelmq/tests/lib/test_harmonization.py

BUG: lib/harm: Handle idna encoding error in FQDN

---

CHANGELOG.md
docs/Feeds.md
intelmq/bots/BOTS
intelmq/bots/parsers/malwareurl/parser.py
intelmq/tests/bots/parsers/malwareurl/test_malwareurl.data
intelmq/tests/bots/parsers/malwareurl/test_malwareurl.py

There is new malwareurl parser, which parse data from website https://www.malwareurl.com/.

Malwareurl parser

---

CHANGELOG.md
docs/Bots.md
intelmq/bots/BOTS
intelmq/bots/experts/wait/expert.py
intelmq/tests/bots/experts/wait/test_expert.py

* Can wait either some time ("rate limiting")
* or until a queue size is below a certain number
* Also has a useful "dummy" mode doing nothing

New expert bot "wait"

---

CHANGELOG.md
docs/Developers-Guide.md
docs/User-Guide.md
intelmq/lib/bot.py
intelmq/lib/pipeline.py
intelmq/lib/test.py
intelmq/tests/bots/experts/cymru_whois/test_expert.py
intelmq/tests/lib/test_bot.py
intelmq/tests/lib/test_expert_bot.py
intelmq/tests/lib/test_pipeline.py

Names queues #1088

---

CHANGELOG.md
docs/Bots.md
intelmq/bots/parsers/twitter/parser.py

Changelog is updated with twitter entries.
Bots.md now contains twitter entries.
Whitelist in twitter parser now works.

Twitter bugfix and docs

---

CHANGELOG.md
docs/Bots.md
docs/Feeds.md
intelmq/bots/BOTS
intelmq/bots/collectors/microsoft/collector_interflow.py
intelmq/bots/parsers/microsoft/parser_ctip.py
intelmq/etc/feeds.yaml
intelmq/tests/bots/parsers/microsoft/ctip.txt
intelmq/tests/bots/parsers/microsoft/test_parser.py

Collector for Interflow API and parser for CTIP data.
Collector has some possibilities to reduce the amount of data to be processed (time- and name-based filter, cache as "memory")

Microsoft Interflow and CTIP

---

CHANGELOG.md
docs/intelmqctl.md
intelmq/bin/intelmqctl.py
intelmq/lib/bot_debugger.py

supports [intelmq-manager-#156 pull](https://github.com/certtools/intelmq-manager/pull/156)

Intelmqctl run show sent

---

CHANGELOG.md
NEWS.md
intelmq/etc/runtime.conf
intelmq/lib/bot.py
intelmq/tests/bots/collectors/http/test_collector.py
intelmq/tests/lib/test_collector_bot.py

DEP: lib/bot: replace parameter feed by name for collectors

---

docs/User-Guide.md

Kindly refer to the rich diff.
Thanks a bunch!

Minor typos and grammar

---

docs/Bots.md
intelmq/bots/BOTS
intelmq/bots/experts/recordedfuture_iprisk/README.md
intelmq/bots/experts/recordedfuture_iprisk/expert.py
intelmq/bots/experts/recordedfuture_iprisk/update-rfiprisk-data
intelmq/tests/bots/experts/recordedfuture_iprisk/iprisk.dat
intelmq/tests/bots/experts/recordedfuture_iprisk/test_expert.py
setup.py

A new expert bot to set risk score associated with either source.ip or destination.ip
It uses data obtained from recorded future API which is a paid and closed service.

Recorded Future IP Risklist expert bot

---

intelmq/lib/pipeline.py

destination queues could contain list or object, not a mere string

named queues doc fix

---

contrib/bash-completion/intelmqctl

autocompletion: missing log keyword

---

CHANGELOG.md
docs/Feeds.md
intelmq/bots/BOTS
intelmq/bots/parsers/surbl/parser.py
intelmq/etc/feeds.yaml
intelmq/tests/bots/parsers/surbl/test_surbl.data
intelmq/tests/bots/parsers/surbl/test_surbl.py

There is new Surbl parser. It parse data from Rsync collector. It is necessarily to have opened up Sponsored Datafeed Service (SDS) access to the SURBL data via rsync to use Surbl parser.

surbl parser

---

CHANGELOG.md
docs/Bots.md
intelmq/bots/BOTS
intelmq/bots/collectors/mail/collector_mail_attach.py
intelmq/bots/collectors/mail/collector_mail_body.py
intelmq/bots/collectors/mail/collector_mail_url.py
intelmq/bots/collectors/mail/lib.py

Body collector is in use at cert.at

Mail Collectors: Body Collector and Common functions

---

CHANGELOG.md
docs/Bots.md
intelmq/bots/collectors/tcp/collector.py
intelmq/bots/outputs/tcp/output.py
intelmq/tests/bots/collectors/tcp/test_collector.py

*  socket timeout added
* when used without separator, IntelMQ output waits the other side tells "Ok" so that the output know the message was acknowledged

TCP more stable version

---

intelmq/bin/intelmqctl.py

[Supervisor](http://supervisord.org) is process manager written in Python. The main advantage is that it take care about processes, so if bot process exit with failure (exit code different than 0), supervisor try to run it again. Another advantage is that it not require writing PID files. 
This manual was tested on Ubuntu 18.04.
Install supervisor. `supervisor_twiddler` is extension for supervisor, that makes possible to create process dynamically. (Ubuntu `supervisor` package is currently based on Python 2, so `supervisor_twiddler` must be installed with Python 2 `pip`.)
```
apt install supervisor python-pip
pip install supervisor_twiddler
```
Create default config `/etc/supervisor/conf.d/intelmq.conf` and restart `supervisor` service:
```ini
[rpcinterface:twiddler] …
```

WIP: Added support for supervisor as process manager

---

intelmq/bots/BOTS
intelmq/bots/parsers/netlab_360/parser.py
intelmq/etc/feeds.yaml

Hello,
I added 5 lines to net360 parser bot to support the hajime scanner list.
Please let me know what i need to impove or change.

added hajime-scanner to net360 parser bot

---

docs/Bots.md
intelmq/bots/BOTS
intelmq/bots/experts/format_field/expert.py
intelmq/tests/bots/experts/format_field/test_expert.py

This multipurpose expert bot can strip characters around fields, replace characters and also can convert string value to list for a field.

Format Field Expert Bot

---

intelmq/bots/parsers/shadowserver/parser.py

Fix https://github.com/certtools/intelmq/issues/1458

Shadowserver Parser fixed config

---

docs/User-Guide.md

The conflict was introduced in commit e7e76cc2a200166e59e7e598f220f7e7a4840806

Fix unresolved conflict in user guide

---

docs/Bots.md
docs/MISP-Integrations.md
intelmq/bots/collectors/misp/collector.py

* fix typo in MISP-Integrations.md
* improve docstring for misp/collector.py

DOC: improve MISP docs

---

docs/Bots.md
docs/Developers-Guide.md
docs/MISP-Integrations.md
intelmq/bots/collectors/misp/collector.py

(on top of https://github.com/Intevation/intelmq/tree/patch-1 so please merge https://github.com/certtools/intelmq/pull/1486 first)

DOC: Update code-examples in Developers-Guide

---

intelmq/bots/parsers/shadowserver/config.py
intelmq/tests/bots/parsers/shadowserver/test_scan_mqtt.py
intelmq/tests/bots/parsers/shadowserver/testdata/scan_mqtt.csv

Add support for Shadowserver Open-MQTT report

Add Shadowserver Open-MQTT

---

intelmq/bots/parsers/bambenek/parser.py

Add additional feed URLs to make the parser happy

Add additional feed URLs

---

docs/ELK-Stack.md

As I had promised via dev mailing list I wrote a guide for setting up Logstash and Elasticsearch for IntelMQ.

Adds ELK setup docs.

---

docs/Bots.md
docs/Feeds.md
intelmq/bots/BOTS
intelmq/bots/collectors/github_api/REQUIREMENTS.txt
intelmq/bots/collectors/github_api/collector_github_api.py
intelmq/bots/collectors/github_api/collector_github_contents_api.py
intelmq/bots/parsers/github_feed/REQUIREMENTS.txt
intelmq/bots/parsers/github_feed/parser.py
intelmq/etc/feeds.yaml
intelmq/tests/bots/collectors/github_api/example_github_repo_contents_response.json
intelmq/tests/bots/collectors/github_api/test_collector.py
intelmq/tests/bots/parsers/github_feed/exmaple_ioc_strangereal_intel.json
intelmq/tests/bots/parsers/github_feed/test_parser.py

Added a new collector bot for collecting  Gihub files via the [Github API](https://developer.github.com/v3/repos/contents/). Additionally, added a new IOC feed from github with corresponding parser bot. All bots are documented as is the feed [StrangerealIntel/DailyIOC](https://github.com/StrangerealIntel/DailyIOC).

GitHub ioc processing

---

intelmq/bots/parsers/shadowserver/config.py
intelmq/tests/bots/parsers/shadowserver/test_scan_coap.py
intelmq/tests/bots/parsers/shadowserver/testdata/scan_coap.csv

Add support for Shadowserver Accessible-CoAP

Add support for Shadowserver Accessible-CoAP

---

intelmq/bots/BOTS
intelmq/bots/collectors/eset/collector.py
intelmq/bots/parsers/eset/parser.py

This PR contains code for two new bots for interfacing with the ESET ETI API, for the JSON-based URL and domain feeds. A new collector is used as there does not currently seem to be a generic TAXII collector.
Any feedback is welcome.

ESET ETI collector/parser bots

---

intelmq/bots/collectors/eset/collector.py

Just some small improvements based on feedback in #1554

ESET collector: distribute message sending, no redundant debug messages

---

intelmq/tests/bots/outputs/elasticsearch/test_output.py

Towards https://github.com/certtools/intelmq/issues/1593
My theory is the test sometimes fails because the document isn't indexed yet (ES does this every 1 second by default, so it could be a race condition with the test's current sleep of 1 second).
I'm not sure how to verify this other than to see if the test still flaps. In any case, it's probably better than sleeping.

Make elasticsearch refresh the index instead of waiting

---

docs/Bots.md
intelmq/bots/BOTS
intelmq/bots/parsers/key_value/parser.py
intelmq/tests/bots/parsers/key_value/test_parser.py

Bot for parsing key=value strings, e.g. in firewall logs.

Add key-value-parser bot

---

docs/Bots.md
intelmq/bots/BOTS
intelmq/bots/experts/threshold/expert.py
intelmq/tests/bots/experts/threshold/test_expert.py

Bot for only propagating messages if a certain number of similar messages arrive in a certain time.

Add threshold expert bot

---

debian/intelmq.postinst

Call upgrade-config and check at debian package upgrades

---

intelmq/bin/intelmqctl.py
intelmq/lib/bot_debugger.py

This way we can use the BotDebugger methods and its return values
internall, resp. it can be used by another tool that wants to somehow
present the output differently (like an API).
One downside is, that the output is being `buffered`, i.e. *all* the
messages are only returned when the BotDebugger `run` method returns.
This also updates the `intelmqctl` script to use the new BotDebugger
interface.

Modify BotDebugger to return output instead of dumping it to stdout

---

CHANGELOG.md
docs/user/bots.rst
intelmq/bots/BOTS
intelmq/bots/collectors/kafka/REQUIREMENTS.txt
intelmq/bots/collectors/kafka/collector.py

Implement a simple Kafka Collector

---

intelmq/bots/parsers/generic/parser_csv.py
intelmq/tests/bots/parsers/generic/sample_report.csv
intelmq/tests/bots/parsers/generic/test_parser_csv.py

Need to ignore line having spaces or tabs only or comment having leading tabs or spaces.

Generic CSV Parser: Ignore tabs and spaces

---

intelmq/bots/experts/national_cert_contact_certat/expert.py
intelmq/tests/bots/collectors/http/test_collector.py

- BUG: Replace dns.query() with dns.resolve()
- BUG: Close the request session after its use
- TST: use a context manager for the mocked files

Remediate some warnings

---

docs/user/FAQ.rst
docs/user/intelmqctl.rst

Some of the code blocks that used the wrong code block syntax
were fixed and some internal references were also corrected.

[DOC] A couple of style fixes in the FAQ

---

docs/user/bots.rst
intelmq/tests/bots/experts/sieve/test_expert.py
intelmq/tests/bots/experts/sieve/test_sieve_files/test_parentheses.sieve

Closes #1681 which asks for either parenthesis or nested if statements.
Given that the former is already possible, the issue can be closed.

Add a testcase that tests if parenthesis work in the sieve language

---

docs/dev/data-harmonization.rst
docs/dev/guide.rst
docs/user/bots.rst
docs/user/installation.rst
docs/user/n6-integrations.rst
intelmq/etc/feeds.yaml

Replace remaining Markdown links with RST links

---

.github/workflows/pycodestyle.yml
.github/workflows/python/github.py
.github/workflows/python/pycodestyle_comment.py
.travis.yml

This also removes the pycodestyle related stuff from travis

Add a github workflow that runs pycodestyle on the repository

---

debian/rules

PKG: Build the sphinx documentation during Debian package creation

---

CHANGELOG.md
docs/user/bots.rst
intelmq/bots/collectors/shadowserverapi/collector.py
intelmq/bots/parsers/shadowserver/jsonparser.py
intelmq/tests/bots/collectors/shadowserverapi/reports-list.json
intelmq/tests/bots/collectors/shadowserverapi/test_collector.py
intelmq/tests/bots/parsers/shadowserver/test_testdata.py

- Add an IntelMQ Shadowserver API collector and JSON parser
- Add tests for the Shadowserver API collector and JSON parser
- Add documentation and changelog entries for Shadowserver API bots

Add Shadowserver API collector and JSON parser

---

docs/user/ecosystem.rst
docs/user/installation.rst
docs/user/upgrade.rst

All docker related changes in documentation.

Docker documentation

---

.github/workflows/codespell.yml
.github/workflows/pycodestyle.yml

MAINT: GitHub Actions - harmonize on which events workflows are executed

---

docs/index.rst
docs/user/intelmq-api.rst

DOC: Integrate documentation for intelmq-api

---

intelmq/etc/harmonization.conf

That makes the harmonisation.conf file more readable.
See also discussion in https://github.com/certtools/intelmq/pull/1709

DOC: replace unicode char with simple asterisk

---

docs/user/intelmq-manager.rst

DOC: some more information about the intelmq-manager setup

---

intelmq/bots/parsers/shadowserver/config.py
intelmq/tests/bots/parsers/shadowserver/test_scan_msrdpeudp.py
intelmq/tests/bots/parsers/shadowserver/testdata/scan_msrdpeudp.csv

Added missing mapping for RDPEUDP data from shadowserver.

ShadowServer is now able to map RDPEUDP data

---

intelmq/bots/parsers/shadowserver/config.py

Updated ShadowServer mapping
Fixes #1733

[FIX] ShadowServer parser http update

---

intelmq/bots/parsers/shadowserver/parser_json.py
intelmq/tests/bots/parsers/shadowserver/test_scan_smb_json.py

ShadowServer now uses recover_line correctly by using recover_line_json.
Fixes #1718

[FIX] Fixes ShadowServer recover_line

---

docs/user/intelmq-api.rst

DOC: fix paths of the intelmq-api configuration files

---

docs/dev/release-procedure.rst
docs/user/installation.rst
docs/user/upgrade.rst

Changes for IntelMQ Docs in order to work with the newer version including the intelmq-api.

[DOCS] Adapted docs for new intelmq-api

---

intelmq/bots/parsers/shadowserver/config.py
intelmq/tests/bots/parsers/shadowserver/test_scan_sinkholedns.py
intelmq/tests/bots/parsers/shadowserver/testdata/scan_sinkholedns.csv

ShadowServer do have correct sinkholeDNS mappings.
Fixes #1716

Added ShadowServer sinkholeDNS mappings

---

CHANGELOG.md
intelmq/bots/experts/maxmind_geoip/expert.py

BUG: fixed handing over of `overwrite` parameter to `event.add`

---

docs/user/intelmq-api.rst

Remove the code blocks showing how to run intelmq-api wiht uwsgi and
gunicorn- thats not useful for endusers.
Rewrite the configuration paragraph and update the default values listed
for reference.
Mention that Debian uses another path for the session file.
Update the user configuration paragraph to mention
``intelmq-api-adduser`` instead of the hug command.

DOC: clean up intelmq-api documentation

---

NEWS.md

Updating news file for 2.3.0

---

docs/conf.py

DOC: set the copyright year to the current year

---

intelmq/lib/utils.py

FIX: set session.verify to the value return from the defaults

---

docs/conf.py

DOC: Set the correct version in generated configuration

---

CHANGELOG.md
NEWS.md
debian/changelog
docs/user/bots.rst
intelmq/bots/BOTS
intelmq/etc/feeds.yaml
intelmq/lib/upgrades.py
intelmq/tests/bots/experts/cymru_whois/test_expert.py
intelmq/tests/lib/test_upgrades.py
intelmq/version.py

final steps for the 2.3.0 release

2.3.0 release

---

CHANGELOG.md
intelmq/lib/utils.py

BUG: lib.utils.log: handle null logging_max_size

---

docs/user/intelmq-api.rst

DOC: add information about session permissions

---

CHANGELOG.md
intelmq/bin/intelmqctl.py
intelmq/bin/intelmqsetup.py

Small intelmqsetup refactoring
intelmqsetup: extend to intelmq-api. fixes #1783

extend intelmqsetup to api

---

docs/dev/guide.rst
docs/user/bots.rst
docs/user/configuration-management.rst

- DOC: Remove the BOTS file from the documentation
- DOC: update documentation regarding the parameters

Update documentation regarding BOTS file and parameter handling

---

intelmq/bin/intelmqctl.py
intelmq/bots/collectors/shadowserver/collector_reports_api.py

FIX: intelmq check uses list_all_bots() correctly

---

.github/workflows/docker.yml

Automated docker image building with github actions

Build docker image with github actions

---

intelmq/bin/intelmqsetup.py

BUG: change string to be f-string

---

CHANGELOG.md
intelmq/bin/intelmqctl.py
intelmq/lib/bot_debugger.py

Set bot's `logging_level` directly in `__init__` before the bot's initialization by changing the default value.
Rewrite `load_configuration_patch` by adapting it to the parameter and configuration rewrite.
If Runtime configuration is detected, the logging_level parameter is
- inserted in all bot's parameters. bot_id is not accessible here, hence we add it everywhere
- inserted in the global parameters (ex-defaults).
Maybe not everything is necessary, but we can make sure the logging_level is just everywhere where it might be relevant, also in the future.
Please review your commits before creating …

BUG: lib/bot_debugger: fix setting the log level

---

intelmq/lib/upgrades.py

BUG: add missing f's to f-strings

---

intelmq/bots/collectors/http/collector_http.py
intelmq/bots/collectors/http/collector_http_stream.py
intelmq/bots/collectors/mail/collector_mail_url.py
intelmq/bots/collectors/microsoft/collector_interflow.py
intelmq/bots/collectors/rt/collector_rt.py
intelmq/bots/collectors/shadowserver/collector_reports_api.py
intelmq/bots/collectors/twitter/collector_twitter.py
intelmq/lib/bot.py
intelmq/lib/mixins/__init__.py
intelmq/lib/mixins/http.py

- Add a HttpMixin
- Use the HttpMixin in the collector bots

Add HTTP Mixin

---

intelmq/bin/intelmqctl.py

using the new private method `_configured_bots_list` code gets cleaner

BUG: ctl: exclude global from more runtime accesses

---

CHANGELOG.md
intelmq/bin/intelmqctl.py
intelmq/bin/intelmqdump.py
intelmq/lib/pipeline.py

FIX: parameter refactoring: fix intelmqdump

---

intelmq/tests/lib/test_pipeline.py

FIX: the pipeline_args should be a dict, not an Parameters object

---

intelmq/bots/parsers/cymru/parser_cap_program.py
intelmq/tests/bots/parsers/cymru/certname_20190327.txt

Fix parsing in whitespace edge case and modify test #1862

---

intelmq/bin/intelmqctl.py

This commit introduces a method _pipeline_configuration() that provides
the same dict the legacy `pipeline_configuration` attribute used to
store.

FIX: recreate the legacy pipeline_configuration

---

intelmq/lib/bot.py
intelmq/tests/lib/test_parser_bot.py

FIX: use a private attribute for log_processed_messages_seconds

---

.github/workflows/build-docs.yml
.github/workflows/codeql-analysis.yml
.github/workflows/codespell.yml
.github/workflows/debian-package.yml
.github/workflows/docker.yml
.github/workflows/nosetests.yml
.github/workflows/pycodestyle.yml

MAINT: don't run all the tests on changes in the .github directory

---

CHANGELOG.md
docs/user/bots.rst
intelmq/bots/experts/rdap/expert.py
intelmq/tests/bots/experts/rdap/test_expert.py

Added the new RDAP expert bot to intelmq.
I accidentally deleted the pre-existing branch or PR #1855

ENH: intelmq.bots.experts.rdap.expert & tests added

---

intelmq/bin/intelmqctl.py

FIX: fix the check method to handle yaml different than json files

---

intelmq/bin/intelmqctl.py

FIX: check for 'parameters' key in dict

---

.github/workflows/debian-package.yml

MAINT: update the fix for the rootless buildah problem

---

docs/dev/guide.rst

DOC: add documentation about Mixins to developers guide

---

CHANGELOG.md
NEWS.md
debian/changelog
docs/dev/release-procedure.rst
docs/user/installation.rst
intelmq/version.py

REL: 2.3.2 Maintenance version

---

.github/workflows/scripts/ansible-playbook.yml

MAINT+FIX: add facts to ansible script

---

intelmq/lib/utils.py

ENH: add some small helper functions

---

CHANGELOG.md
intelmq/bin/intelmqctl.py
intelmq/bots/experts/asn_lookup/expert.py
intelmq/bots/experts/domain_suffix/expert.py
intelmq/bots/experts/maxmind_geoip/expert.py
intelmq/bots/experts/recordedfuture_iprisk/expert.py
intelmq/bots/experts/tor_nodes/expert.py
intelmq/lib/utils.py
intelmq/tests/lib/test_utils.py

BUG: skip global in expert's database update routines

---

CHANGELOG.md
docs/index.rst
docs/user/configuration-management.rst
intelmq/bots/parsers/shadowserver/_config.py

Changed data-harmonization to data-format & some whitespaces :woozy_face: 
Closes #1853

DOCS: Renamed data-harmonization to data-format

---

CHANGELOG.md
NEWS.md
intelmq/etc/feeds.yaml
intelmq/lib/upgrades.py
intelmq/tests/bots/parsers/html_table/feodotracker.html
intelmq/tests/bots/parsers/html_table/test_feodotracker.py
intelmq/tests/lib/test_upgrades.py

- adapted docs
- added news entry
- added upgrade config
- added upgrade config test
- added html table parser test
#1938

BUG/DOC: updated feodotracker browse parser confiuration

---

intelmq/tests/bots/experts/threshold/test_expert.py

don't sleep, just flush the database
set the common parameters once
use the dedicated test database, works around a bug:
BotTestCase.setUpClass sets up the cache, but it doesn't know of the
redis database which the test will use. So let's just use the same.
fixes a test fail of #1939

TST: simplify threshold tests

---

CHANGELOG.md
intelmq/bots/parsers/microsoft/parser_ctip.py
intelmq/tests/bots/parsers/microsoft/test_parser_ctip_azure.py

044549a838eca8b7acdf0d348a7553364c83eaf5 should have been part of this PR as well, but I erroneously pushed to the wrong upstream branch :/

BUG: ctip parser: fix ConnectionType mapping

---

.github/workflows/scripts/debian-package.sh

ENH: Disable tests when we build Debian packages

---

CHANGELOG.md
docs/user/bots.rst
intelmq/bots/outputs/smtp/output.py
intelmq/tests/bots/outputs/smtp/test_output.py

by sending no attachment
includes docs and test case

smtp output: handle empty fieldnames parameter

---

intelmq/bots/collectors/microsoft/collector_azure.py
intelmq/bots/collectors/microsoft/collector_interflow.py
intelmq/bots/collectors/shadowserver/collector_reports_api.py
intelmq/bots/experts/cymru_whois/expert.py
intelmq/bots/experts/deduplicator/expert.py
intelmq/bots/experts/rdap/expert.py
intelmq/bots/experts/reverse_dns/expert.py
intelmq/bots/experts/ripe/expert.py
intelmq/bots/experts/threshold/expert.py
intelmq/lib/bot.py
intelmq/lib/mixins/__init__.py
intelmq/lib/mixins/cache.py
intelmq/lib/mixins/http.py

The Cache mixin replaces the lib.cache implementation. Its easier to inherit & keeps the code more clean.

ENH: Cache mixin

---

intelmq/bots/parsers/shadowserver/config.py
intelmq/tests/bots/parsers/shadowserver/test_scan_exchange.py
intelmq/tests/bots/parsers/shadowserver/testdata/scan_exchange.csv

ENH: add Shadowserver scan_exchange config & tests

---

docs/user/bots.rst
intelmq/bots/collectors/rt/collector_rt.py

DOC: rt collector: document search_requestor parameter

DOC: rt collector: document search_requestor parameter

---

CHANGELOG.md
contrib/eventdb/README.md
contrib/eventdb/separate-raws-table.sql
docs/user/FAQ.rst
docs/user/eventdb.rst

Adds an introduction for the events table itself and on top of it how to separate the "raw" data

EventDB: Instructions to separate raw data

---

CHANGELOG.md
docs/user/bots.rst
intelmq/bots/experts/aggregate/expert.py
intelmq/lib/test.py
intelmq/tests/bots/experts/aggregate/test_expert.py

Please especially check if `counter_ignored` is implemented correctly

Aggregate expert Test and docs fixes

---

CHANGELOG.md
NEWS.md
docs/dev/data-format.rst
intelmq/bots/experts/idea/expert.py
intelmq/bots/experts/taxonomy/expert.py
intelmq/bots/parsers/cert_eu/parser_csv.py
intelmq/bots/parsers/cymru/parser_cap_program.py
intelmq/bots/parsers/misp/parser.py
intelmq/bots/parsers/zoneh/parser.py
intelmq/lib/harmonization.py
intelmq/tests/bots/experts/field_reducer/test_expert.py
intelmq/tests/bots/experts/filter/test_expert_absolute_after.py
intelmq/tests/bots/experts/filter/test_expert_absolute_before.py
intelmq/tests/bots/experts/filter/test_expert_regex_search.py
intelmq/tests/bots/experts/filter/test_expert_relative_after.py
intelmq/tests/bots/experts/filter/test_expert_relative_before.py
intelmq/tests/bots/experts/filter/test_extra.py
intelmq/tests/bots/experts/filter/test_paths.py
intelmq/tests/bots/experts/taxonomy/test_expert.py
intelmq/tests/bots/parsers/zoneh/test_zoneh.py
intelmq/tests/lib/test_harmonization.py

merged into information-content-security > unauthorised-information-modification
adapt bots depending on the name
add changelog and news entries, including SQL update statements
based on #1992 and #1993 to prevent merge conflicts

harm: remove type defacement

---

CHANGELOG.md
docs/user/eventdb.rst

Brief description of time-series & how to install.

DOCS: Added timescaleDB extension

---

docs/user/bots.rst
intelmq/bots/experts/trusted_introducer_lookup/expert.py
intelmq/tests/bots/experts/trusted_introducer_lookup/test_data/teams.json
intelmq/tests/bots/experts/trusted_introducer_lookup/test_data/teams.json.license
intelmq/tests/bots/experts/trusted_introducer_lookup/test_expert.py
setup.cfg

Downloads teams.json from trusted introducer and then
tries to find an abuse contact via a given domain or asn.
IP Addresses are also possible, but not added yet!

ENH: Added trusted introducer expert

---

intelmq/bots/parsers/zoneh/parser.py
intelmq/lib/bot.py

the internal variable handle and current_line were not prefixed with an
underscore, so they were detected as parameters.

BUG: lib/bot: ParserBot: mark internal variables correctly

---

intelmq/etc/feeds.yaml

Hello,
Here is an updated version of the YAML feed configuration file that integrates one of the Benkow feeds.
Source page: http://benkow.cc/passwords.php
Feel free to give me feedback if my commit needs to be changed.
Thanks

Feeds documentation: Add benkow panels tracker

---

CHANGELOG.md
docs/user/bots.rst
intelmq/bots/experts/tuency/expert.py
intelmq/lib/utils.py
intelmq/tests/bots/experts/tuency/test_expert.py
intelmq/tests/lib/test_utils.py

ENH: add tuency expert

---

docs/user/FAQ.rst
docs/user/installation.rst
docs/user/intelmq-api.rst

Updated docker-compose install instructions

DOCS: Docker-compose commands updated

---

docs/user/bots.rst

DOCS: Added better description for trusted introducer

---

CHANGELOG.md
intelmq/bin/intelmqctl.py

BUG: ctl: honour environment parameters

---

CHANGELOG.md
intelmq/bots/experts/gethostbyname/expert.py
intelmq/tests/bots/experts/gethostbyname/test_expert.py

BUG: gethostbyname: handle numeric gaierrors_to_ignore

---

intelmq/lib/upgrades.py

BUG: fix v300_pipeline_file_removal

---

docs/REST-API.md

@aaronkaplan As agreed I submit my suggestion of simple management REST API for 3.0 ideas.

REST API ideas for 3.0
