certtools/intelmq

intelmq/conf/system.conf
Sets as #237 does the default loglevel in conf/system.conf to 
INFO as it was criticized by @aaronkaplan in #210 but for the master branch.
=> Fix set default loglevel to INFO in conf/system.conf

intelmq/bots/BOTS, intelmq/bots/experts/asn_lookup/expert.py
An event without source.ip or destination.ip can't go through asn_lookup expert and is just discarded.
=> ASN lookup discarding events

intelmq/bin/intelmqctl, intelmq/lib/pipeline.py, intelmq/lib/utils.py
* ENH: intelmqctl uses print_function
* BUG: intelmqctl silently exits in undefined function
* ENH: intelmqctl command line argument shorthands
* ENH: intelmqctl log parsing/reading simplified
The logs are read and parsed backwards, which is more efficient than reading and parsing the entire file from the beginning
The code to read the file is easier to read and understand now, however some code in utils reads the file backwards in chunks.
This change is currently not compatible with intelmq-manager as it wants to read the line number which is not read anymore as its not possible to get it by reading the file backwards. Yet a line number does not make sense in log files.
See certtools/intelmq-manager#53
* ENH: intelmqctl logs to file and add stream logger
intelmqctl has a log file as …
=> Intelmqctl

REQUIREMENTS, REQUIREMENTS3, intelmq/bin/intelmqdump, intelmq/lib/bot.py, intelmq/lib/utils.py, setup.py
New interactive tool to read and analyze dumped messages. Recover all or some of the dumped messages.
It lists all dumps, showing the counted messages in it, or corrupt files. Select the dump to process and have the choice to show a formatted version of the message, recover it, delete single messages from a dump file, etc.
Visual enhancements to the terminal (bold, inverted or red fonts) indicate important messages, inputs and errors!
=> intelmqdump: Inspect dumps and reinject messages!

intelmq/bots/outputs/restapi/output.py
- explicit headers for content-type and charset are needed by some applications
- exception could be raised even without response r being initialized
=> restapi enhancements

docs/Bots.md, docs/User-Guide.md, intelmq/bin/intelmqdump, intelmq/bots/BOTS, intelmq/bots/experts/modify/expert.py, intelmq/bots/experts/modify/modify.conf, intelmq/bots/experts/rfc1918/expert.py, intelmq/bots/parsers/blocklistde/parser.py, intelmq/bots/parsers/dragonresearchgroup/parser_ssh.py, intelmq/lib/cache.py, intelmq/lib/test.py, intelmq/tests/bots/experts/cymru_whois/test_expert.py, intelmq/tests/bots/experts/modify/test_expert.py, intelmq/tests/bots/experts/reverse_dns/test_expert.py, intelmq/tests/bots/experts/rfc1918/test_expert.py
The fixes from the last week:
- intelmqdump truncates long raw fields
- intelmqdump can inject into arbitrary queues  by given name
- modify bot has more extensive default config (it's not special for any cert)
-  the RFC1918 bot can clean FQDNs and URLs
- the tests for cymru and reversedns clean the cache after finishing (caused problems because of identical keys)
- IPv6 test for reverse dns
- bugfix for #346
=> several fixes: bugfixes, modify bot config, intelmqdump

docs/User-Guide.md, intelmq/conf/defaults.conf, intelmq/conf/runtime.conf, intelmq/lib/bot.py, intelmq/lib/test.py, intelmq/tests/lib/test_bot.py
**Notes:**
1. `error_traceback` variable is because in `finally:` section of the `try:except` is not possible to get the exception message through `traceback.format_exc()`. New approaches are welcome! :)
2. In case of pipeline error, the message will not be dumped because it stills saved on pipeline. I think the dumped message will not add extra value to the system in this specific situation.
3. This pull req keeps a bug which already exists (https://github.com/SYNchroACK/intelmq/blob/error_handling/intelmq/lib/bot.py#L149)
4. The new behavior of error handling is described in documentation. Feedback is welcome!
@sebix , your feedback on this is a must! :p Thank you.
fix #326 
fix #316
=> ENH: new error handling

CHANGELOG.md, docs/Data-Harmonization.md, docs/Harmonization-fields.md, intelmq/bots/collectors/alienvault_otx/collector.py, intelmq/bots/collectors/http/collector_http.py, intelmq/bots/collectors/http/collector_http_stream.py, intelmq/bots/collectors/mail/collector_mail_attach.py, intelmq/bots/collectors/mail/collector_mail_url.py, intelmq/conf/defaults.conf, intelmq/conf/harmonization.conf, intelmq/lib/harmonization.py, intelmq/lib/message.py, intelmq/tests/lib/test_message.py
This pull request adds an accuracy feature that is meant to represent the amount of false positives the feed has. Say you have a feed with 10 false positives for every 100 events, than you would give it a 90 in the accuracy parameter (as in 90%).
The reason I put a quantitative value (0 to 100), instead of a qualitative value (low, medium, high), was because I was thinking that, in the future, a feedback loop could be done in which the operators give feedback to the system regarding whether a given event is correctly identified or not, and that could be used to automatically calculate the feed's accuracy.
Although it is not hard to change it into a qualitative value if you guys prefer. What do you think is the best option?
=> ENH: Accuracy feature for all feeds

intelmq/conf/harmonization.conf
Extended regex for malware name. Changes based on observation of incidents from N6.
More details available here: https://github.com/certtools/intelmq/issues/412
=> ENH: malware.name - loosen regex

intelmq/lib/harmonization.py
according to 
https://www.enisa.europa.eu/activities/cert/support/incident-management/browsable/incident-handling-process/incident-taxonomy/existing-taxonomies
"other" is a valid classification. Add it.
=> other is a valid eCSIRT II classification

intelmq/bots/parsers/generic/parser_csv.py, intelmq/tests/bots/parsers/generic/test_parser_csv2.py
Generic csv parser now allows to define translation for classification.type based on the value in one of the report values.
```
"type_translation": "{\"malware site\": \"malware\"}"
```
=> ENH: generic csv parser type_translation

intelmq/bots/BOTS, intelmq/bots/collectors/xmpp/REQUIREMENTS.txt, intelmq/bots/collectors/xmpp/collector.py, intelmq/bots/outputs/xmpp/REQUIREMENTS.txt, intelmq/bots/outputs/xmpp/output.py
This includes the code for both the collector and the output bots. Code is a tidied up version of the code from PRs 158 and 197, as well as the comments there.
Thanks to @helderfernandes1279 for the original code.
=> Add code for XMPP bots

docs/User-Guide.md, intelmq/bin/intelmqctl.py
As proposed in certtools/intelmq#474, this changes the syntax for intelmqctl.
Will provide fixes for intelmq-manager if there are no objections here.
```
$ intelmqctl -h
usage: 
intelmqctl [start|stop|restart|status|run] bot-id
intelmqctl [start|stop|restart|status]
intelmqctl list [bots|queues]
intelmqctl log bot-id [number-of-lines [log-level]]
intelmqctl clear queue-id
Starting a bot:
intelmqctl start bot-id
Stopping a bot:
intelmqctl stop bot-id
Restarting a bot:
intelmqctl restart bot-id
Get status of a bot:
intelmqctl status bot-id
Run a bot directly (blocking) for debugging purpose:
intelmqctl run bot-id
Starting the botnet (all bots):
intelmqctl start
etc.
Get a list of all configured bots:
intelmqctl list bots
Get a list of all queues:
intelmqctl list queues
Clear a queue: …
```
=> Revised intelmqctl parameter sytnax

intelmq/bots/collectors/ftp/collector_ftp.py, intelmq/bots/collectors/ftp/collector_ftps.py, intelmq/tests/bots/collectors/ftp/test_collector_ftp.py, intelmq/tests/bots/collectors/ftp/test_collector_ftps.py
Bots for collecting files from FTP and FTPS, both bots include automatic unzipping
Possible issue is no proxy support
=> BOT: collector ftp(s)

intelmq/bots/experts/taxonomy/expert.py
This Fixes https://github.com/certtools/intelmq/issues/525
I also checked if all other classification.types are available:
Result: Yes they are.
=> Added Classification.Type other to TAXONOMY Expert bot.

docs/Bots.md
From the description the link to the python doc should be towards the beginning of the string format syntax, not the mini-language section.
(I was searching the '{' description for a while there until I've noticed I had to scroll up to find it)
=> Update Bots.md: Modify description.

docs/Developers-Guide.md, intelmq/bots/parsers/abusech/parser_domain.py, intelmq/bots/parsers/abusech/parser_ip.py, intelmq/bots/parsers/alienvault/parser.py, intelmq/bots/parsers/arbor/parser.py, intelmq/bots/parsers/autoshun/parser.py, intelmq/bots/parsers/blocklistde/parser.py, intelmq/bots/parsers/dragonresearchgroup/parser_ssh.py, intelmq/bots/parsers/dragonresearchgroup/parser_vnc.py, intelmq/bots/parsers/generic/parser_csv.py, intelmq/bots/parsers/malwaredomainlist/parser.py, intelmq/bots/parsers/vxvault/parser.py, intelmq/lib/bot.py, intelmq/lib/test.py, intelmq/tests/bots/parsers/autoshun/shunlist.html, intelmq/tests/bots/parsers/autoshun/test_parser.py, intelmq/tests/bots/parsers/malwaredomainlist/test_parser.py, intelmq/tests/bots/test_dummy_bot.py
An additional possibility for parsers.
The parsing of the text itself (splitlines in the simplest case) has been separated from the parsing of individual lines. Now, single lines can be dumped.
As small drawback, we need now mechanisms to reconstruct the original messages, but this is usually a one-liner (see examples).
This also lowers the complexity.
All changes are backwards-compatible, parsers using `process()` work fine, nothing changed for them.
This is a proof-of-concept, ready for reviews.
Still missing: docs for devs, tests, more conversions
refers to #374, #513 and #405
ping at @robcza @SYNchroACK @aaronkaplan @ondj @mauroasilva (everybody how participated in linked discussions)
=> New parser's architecture, dumping of individual messages

intelmq/bots/parsers/shadowserver/config.py
Remove the rule for the field "username" from the shadowserver parser's
configuration for the Open-Mongo DB feed because it does not actually
exist in the feed. In the new parser fails to parse the feed as a
consequence (which is a good thing!).
=> shadowserver's Open-Mongo DB feed does not have a username field

intelmq/lib/harmonization.py, intelmq/tests/lib/test_harmonization.py
Increase the possibility of successful DateTime parsing by enabling fuzzy parser. This also allows removing explicit fuzzy parsing from the CSV parser and rely on the sanitization process only.
=> fuzzy DateTime parsing

debian/intelmq.postinst
Only change permissions of its contents, i.e., `var` and `etc`.
This should resolve #559.
=> Deb package: Change fewer intelmq home dir permissions

debian/rules
A regular Python installation places the modify expert bot example
configs in /opt/intelmq/var/lib/bots/modify/example.  The deb package
copies them to the bot's documentation directory in
/usr/share/doc/intelmq.
This patch removes the files from their original location to avoid
duplication.
=> Deb package: Remove redundant modify bot example configs

intelmq/bots/BOTS, intelmq/bots/collectors/file/collector_file.py, intelmq/bots/experts/filter/expert.py, intelmq/bots/parsers/alienvault/parser.py, intelmq/bots/parsers/shadowserver/parser.py, intelmq/bots/parsers/vxvault/parser.py, intelmq/lib/bot.py, intelmq/lib/test.py, intelmq/tests/bots/parsers/vxvault/test_parser.py, intelmq/tests/bots/test_dummy_bot.py
This reduces the runned bot-tests drastically from 805 to 322 and the time needed from 80s to 12s while remaining coverage.
Also, some tests haven't been effective, thus and many small issues in the bots have been fixed (missing leading dots, wrong imports, totally broken vxvault parser).
Signed-off-by: Sebastian Wagner <sebix@sebix.at>
=> TST: Reduce number of bot tests and fix log errors

intelmq/bots/collectors/mail/collector_mail_attach.py, intelmq/bots/collectors/mail/collector_mail_url.py
This patch adds an explicit mailbox.close() command to end the IMAP
connection.  Without this, mail does not get marked as \Seen reliably.
=> Mail collectors: explicitly close IMAP connection

intelmq/bots/parsers/misp/parser.py
Raw field previously contained the entire MISP event for each attribute, resulting in massive duplication. It now just stores the JSON data for the MISP attribute.
=> Fixed MISP parser issue with raw field

intelmq/bots/collectors/rt/collector_rt.py
Fortunately, the time is already UTC (at least in `get_history` as opposed to `get_ticket`m which has local time...)
=> RT collector: use observation time from RT-ticket

docs/User-Guide.md
* Fixed link to FAQ. (Because the url is in the left brackets with markdown.)
* Added links to the Bots.md documentation, because there was no way
from the top-level README.md to get to the bots documentation.
User-Guide.md was a natural place to have at least one link.
=> DOCS: improved.

intelmq/lib/test.py, intelmq/tests/bots/test_dummy_bot.py, intelmq/tests/lib/test_bot.py, intelmq/tests/lib/test_message.py, setup.py
mock is now part of the Python standard library, available as
unittest.mock in Python 3.3 onwards. As we require python3.3,
we can use unittest.mock and remove the requirement for an external mock.
(closes #659 https://github.com/certtools/intelmq/issues/659)
=> TESTS: (minor) cleanup: Using unittest.mock now.

intelmq/bin/intelmqctl.py, intelmq/bots/collectors/alienvault_otx/collector.py, intelmq/bots/collectors/bitsight/collector.py, intelmq/bots/collectors/blueliv/collector_crimeserver.py, intelmq/bots/collectors/file/collector_file.py, intelmq/bots/collectors/ftp/collector_ftp.py, intelmq/bots/collectors/ftp/collector_ftps.py, intelmq/bots/collectors/http/collector_http.py, intelmq/bots/collectors/http/collector_http_stream.py, intelmq/bots/collectors/mail/collector_mail_attach.py, intelmq/bots/collectors/mail/collector_mail_url.py, intelmq/bots/collectors/misp/collector.py, intelmq/bots/collectors/n6/collector_stomp.py, intelmq/bots/collectors/rt/collector_rt.py, intelmq/bots/collectors/xmpp/collector.py, intelmq/bots/parsers/shadowserver/parser.py, intelmq/lib/bot.py, intelmq/lib/test.py, intelmq/tests/bots/test_dummy_collectorbot.py
Solves a few issues:
https://github.com/certtools/intelmq/issues/607#issuecomment-235059314
https://github.com/certtools/intelmq/commit/4aa799a7095a51b74fb2303c0e46c8d18a8131b6 
#601 
* automatically ignores reports without raw
* automatically adds `feed.name`, `feed.code` and `feed.accuracy`
=> Create and Use CollectorBot

docs/Bots.md, intelmq/bots/outputs/postgresql/README.md
* Linking the postgresql and psycopg documentation.
* Completing the information with default values.
* Linking REQUIREMENTS.txt, removing one duplication of infos.
* links the README.md from docs/Bots.md
* added explanation for the two ways to set up a) local b) network
* createuser: moving to non-interative and --no-createrole for
a higher priviledge separation,as createdb can always be done
by the database-superuser.
* postgresql version: recommending v>=9.4 linking the rationale,
allowing any supported version
resolves #711
=> DOCS: outputs/postgresql: improved.

docs/Feeds.md, intelmq/bots/BOTS, intelmq/tests/test_conf.py
Reorganization of BOTS file and more documentation
=> Fixes certtools/intelmq#668.

docs/Harmonization-fields.md, intelmq/bots/BOTS, intelmq/etc/harmonization.conf, intelmq/lib/bot.py, intelmq/lib/message.py, intelmq/tests/bin/initdb.sql, intelmq/tests/bots/test_dummy_collectorbot.py
This implements #725 (also mentioned in #733) and includes some typo fixes.
This only adds `feed.provider` to the DHO and implements adding it to the report if the parameter `provider` is set in a collector (analogous to `feed.code`). Whether this value is set in the parsers is still open for discussion.
=> Add "feed.provider" to the DHO

intelmq/bin/intelmqdump.py
- Handle EOF for user input
- Hide the possibly very long list after show command
- deny recovery for running bots (see also certtools/intelmq#574)
- handle missing ids for `r` command
- boost recovery performance by saving files only once at the end
=> intelmqdump improvements

docs/Bots.md, intelmq/lib/bot.py, intelmq/lib/utils.py
This introduces the enabled-switch for all Collector-Bots.
By doing so it fixes #715.
The Collectorbot was extended with an own start-function
which checks if the enabled parameter is present and was set
to a representation of False. To check the "representation of
False" the function to_bool was introduced in utils.py, which
maps well-known-text to booleans. It has a a fallbackmode parameter
which determines if the function returns true of false if no
mapping  was found.
As long as to_bool does not evaluate to False the bot will be started.
=> Introduction of the Enabled-Switch for Collectors.

docs/Feeds.md, intelmq/bots/BOTS, intelmq/bots/parsers/nothink/parser.py, intelmq/tests/bots/parsers/nothink/blacklist_snmp_day.txt, intelmq/tests/bots/parsers/nothink/test_parser.py
Nothink provides data from Honeypots. The needed files have been created or updated to allow for this parser to be used easily for the feeds offered by nothink.org
=> Parser for Nothink data feed

docs/User-Guide.md, intelmq/lib/cache.py, intelmq/lib/pipeline.py
UNIX socket can be faster (see http://redis.io/topics/benchmarks) and sometimes is easier to connect Redis with a socket instead of TCP.
=> Redis UNIX socket support

docs/User-Guide.md, intelmq/bots/BOTS, intelmq/bots/experts/cymru_whois/expert.py, intelmq/bots/experts/deduplicator/expert.py, intelmq/bots/experts/reverse_dns/expert.py, intelmq/etc/defaults.conf, intelmq/lib/cache.py, intelmq/lib/pipeline.py
In some cases (for example `rhscl/redis-32-rhel7` RedHat Docker image) is required to run password protected Redis. This pull makes this possible for Pipeline and Cache.
=> Added ability to connect password protected Redis

docs/README.rst
After moving the README to docs/ the relative paths to further documentation changed...
=> Fixed relative paths in links

intelmq/bots/outputs/xmpp/output.py, intelmq/lib/message.py
In order to process events sent by XMPP within
the JSON-Parser, the to_json method of a message
needed to be extendet to add the type
of the message
=> Extended to_json with a "with_type" option.

intelmq/bots/BOTS, intelmq/bots/experts/reverse_dns/expert.py
For 60 or 3600 seconds, because in some cases response can take 5 seconds and it can slow down the whole queue.
=> Cache also invalid responses from DNS server in reverse_dns bot

docs/Bots.md, docs/User-Guide.md
Fixes certtools/intelmq#825.
After much discussion and misunderstanding, I think this is what we decided on in #825. This  PR replaces #830 and #838. 
Changes for the intelmq-manager are still needed. See issue certtools/intelmq-manager#92
=> Clarify 'enabled' switch

intelmq/bots/collectors/mail/collector_mail_attach.py, intelmq/bots/collectors/mail/collector_mail_url.py
E-mail subject can contain newlines characters, but in e-mail format, it is only separator with no meaning. And without removing, subject regex can stop working anytime for a long subject.
=> Remove new lines from mail subject in mail collector

docs/Harmonization-fields.md, intelmq/bots/parsers/anubisnetworks/parser.py, intelmq/lib/harmonization.py, intelmq/tests/lib/test_harmonization.py
Allows non-string values to be uses for events (for sanitation). They will now be converted to strings automatically. And allow host bits for networks in sanitation.
And docs of course :)
Also a very small step towards #671
=> Dev sanitize ip

intelmq/bots/parsers/shadowserver/config.py
This fixes https://github.com/certtools/intelmq/issues/864 by moving "destination" to "source".
**Only necessary if you are running a setup that is already using the Shadowserver Open-LDAP, or has been using this feed**
1) This commit will require migrations in the EventDB, an example SQL-statement will be provided in issue #864, soon
2) If you are using Filter-Experts looking for the key `destination.local_hostname`, you need to update them to `source.local_hostname`
=> Changed keymapping in Shadowserver Open-LDAP config

intelmq/etc/pipeline.conf, intelmq/etc/runtime.conf
This extends the current example configuration. Now 4 different free feeds are configured: Abuse.ch, Spamhaus, malware domain list (was already default) and malc0de.
Also, some very useful experts: deduplicator, taxonomy, url2fqdn, gethostbyname, taxonomy and cymru.
The only output is still the file, all other would need proper configurations.
Additionally I added two instances for the gethostbyname (because of the lookups) to demonstrate a useful example to load balancing.
fixes certtools/intelmq#357
=> Provide bigger & diversified example config

intelmq/bin/intelmqctl.py
If we know that the bot is running after 0.25s, we should not remove the pid file. If the bot needs some more time, the file will be removed once `intelmqctl status` is called anyway.
related:
certtools/intelmq#763
certat/intelmq#92
=> intelmqctl: only remove pid file when actually stopped

docs/User-Guide.md, intelmq/bin/intelmqctl.py, intelmq/lib/utils.py
In case of misconfigrations or incomplete installations, better error messages/warnings are shown. Also `check` is now capable of checking the existence of bot executables.
If `-q` is given, non-empty queues are not shown.
Now, argparse validates all given actions and parameters. This gives much better help and error messages, e.g.:
```
$ intelmqctl status --help
usage: intelmqctl status [-h]
[{file-output,abusech-feodo-domains-collector,abusech-domain-parser,deduplicator-expert}]
positional arguments:
{file-output,abusech-feodo-domains-collector,abusech-domain-parser,deduplicator-expert}
optional arguments:
-h, --help            show this help message and exit
```
or:
```
$ intelmqctl list
usage: intelmqctl list [-h] [--quiet] {bots,queues}
intelmqctl list: error: the following arguments …
```
=> intelmqctl argument parsing and error handling

docs/Bots.md, intelmq/bots/BOTS, intelmq/bots/outputs/restapi/output.py
Fixes bugs:
* missing parameter use_json in BOTS
* some missing parameters in docs plus explanation
* errors during sending led to data loss
Newly added feature: HTTP Basic Authentication instead of using headers and new parameter auth_type to chose between authentication types.
=> REST API output: fixes and HTTP Basic Authentication

README.rst
https://bitbucket.org/clarifiednetworks/abusehelper says:
> This repository has been deleted
>
> Our apologies, but the repository "abusehelper" has been deleted.
>
> It now lives at https://github.com/abusesa/abusehelper.
This pull request fixes this in `README.rst`.
=> Fix URL of AbuseHelper

intelmq/bots/parsers/anubisnetworks/parser.py, intelmq/tests/bots/parsers/anubisnetworks/test_parser.py
Fixes the incomplete PR #903 #904 
`_origin`, `_provider` and `pattern_verified` are not in `env`.
For pattern_verified I had no sample to verify it.
And added tests for it.
=> BUG: anubis parser: Fix incomplete extra fields

intelmq/lib/bot.py
In case of an error, it will be logged as error anyway.
But a regular kill is not an error.
=> Reduce error messages: Exiting is not an error

intelmq/bots/parsers/shadowserver/config.py, intelmq/tests/bots/parsers/shadowserver/compromised_website.csv, intelmq/tests/bots/parsers/shadowserver/compromised_website_RECONSTRUCTED.csv, intelmq/tests/bots/parsers/shadowserver/test_compromised_website.py
Recently, some occurences of compromised-website reports were not sound: the 'url' value did not start with a /. As a consequence, the resulting 'source.url' field was erroneous, since it is the concatenation of 'hostname' + 'url'.
Example:
...,"hostname",...,"url",...
...,"example.com",...,"blip.php",...
results in: "http://example.comblip.php" instead of "http://example.com/blip.php"
=> Shadowserver Compromised-Website: handle missing / in URL

intelmq/lib/harmonization.py, intelmq/tests/bots/experts/taxonomy/test_expert.py
New category `test` to be consistent and add test to ensure this consistence.
thanks to @pharook for the hint
=> BUG+TST: complete types list in taxonomy expert

intelmq/bots/BOTS, intelmq/bots/collectors/rt/README.md, intelmq/bots/collectors/rt/collector_rt.py, intelmq/bots/experts/filter/expert.py, intelmq/lib/utils.py, intelmq/tests/lib/test_utils.py
* If a resource needs to be fetched via download and the resource is not available, we now skip the creation of a report. (bugfix) Also, the ticket status will be changed according to the configuration
* Allows optional time-based searches, both absolute and relative, see the added docs.
=> RT collector: error handling and time filtering

intelmq/bin/intelmqctl.py, intelmq/lib/bot.py, intelmq/lib/exceptions.py, intelmq/lib/pipeline.py
Two bugs are fixed:
* Handle non existing src or dest queues
Currently, a bot without destination queue is retrying forever, now it stops immediately with a ConfigurationError
* bots handle invalid keys in incoming messages
If an incoming message does contain an key/value which is not valid, we are retrying too, now it stops immediately with a ConfigurationError
=> Better handle misconfigurations by stopping the bot

.travis.yml, docs/Developers-Guide.md, intelmq/bots/collectors/alienvault_otx/collector.py, intelmq/lib/test.py, intelmq/tests/bots/collectors/alienvault_otx/test_collector.py, intelmq/tests/bots/collectors/blueliv/test_collector.py, intelmq/tests/bots/collectors/mail/test_collector_attach.py, intelmq/tests/bots/collectors/mail/test_collector_url.py, intelmq/tests/bots/collectors/misp/test_collector_attach.py, intelmq/tests/bots/collectors/n6/test_collector.py, intelmq/tests/bots/collectors/rt/test_collector.py, intelmq/tests/bots/collectors/xmpp/test_collector.py, intelmq/tests/bots/experts/maxmind_geoip/test_expert.py, intelmq/tests/bots/outputs/amqptopic/test_output.py, intelmq/tests/bots/outputs/elasticsearch/test_output.py, intelmq/tests/bots/outputs/mongodb/test_output.py, intelmq/tests/bots/outputs/postgresql/test_output.py, intelmq/tests/bots/outputs/stomp/test_output.py, intelmq/tests/bots/outputs/xmpp/test_output.py
Makes testing easier if not all libraries are installed:
* OTXv2
* python-rt
* sleekxmpp
* imbox
* pymisp
* geoip2
* stomp
* pika
* elasticsearch
* pymongo
Components depending on these libs can be tested by setting `INTELMQ_TEST_EXOTIC=1` (default on travis).
Motivation: Run tests in build environment where I don't have all this libs, but also very useful for devs.
=> Tests: Lazy imports of some libs

intelmq/bots/collectors/http/collector_http_stream.py, intelmq/lib/bot.py
Fixes two issues with SIGHUP handling:
* Logging in shutdown methods works again (e.g. done in XMPP bots)
* HTTP stream collector reloads correctly
=> sighup handling fixes

intelmq/bin/intelmqctl.py, intelmq/bots/collectors/file/collector_file.py, intelmq/bots/collectors/ftp/collector_ftp.py, intelmq/bots/collectors/ftp/collector_ftps.py, intelmq/bots/collectors/http/collector_http.py, intelmq/bots/collectors/http/collector_http_stream.py, intelmq/bots/collectors/mail/collector_mail_url.py, intelmq/bots/collectors/microsoft/collector_azure.py, intelmq/bots/collectors/n6/collector_stomp.py, intelmq/bots/collectors/rt/collector_rt.py, intelmq/bots/collectors/xmpp/collector.py, intelmq/bots/experts/asn_lookup/expert.py, intelmq/bots/experts/filter/expert.py, intelmq/bots/experts/generic_db_lookup/expert.py, intelmq/bots/experts/maxmind_geoip/expert.py, intelmq/bots/experts/modify/expert.py, intelmq/bots/experts/rfc1918/expert.py, intelmq/bots/outputs/amqptopic/output.py, intelmq/bots/outputs/file/output.py, intelmq/bots/outputs/mongodb/output.py, intelmq/bots/outputs/postgresql/output.py, intelmq/bots/outputs/redis/output.py, intelmq/bots/outputs/tcp/output.py, intelmq/bots/outputs/udp/output.py, intelmq/bots/outputs/xmpp/output.py, intelmq/bots/parsers/cleanmx/parser.py, intelmq/bots/parsers/n6/parser_n6stomp.py, intelmq/bots/parsers/shadowserver/parser.py, intelmq/lib/bot.py
pylint warnings 1201 and 1202:
```
> pylint --help-msg W1201
No config file found, using default configuration
:logging-not-lazy (W1201): *Specify string format arguments as logging function parameters*
Used when a logging statement has a call form of "logging.<logging
method>(format_string % (format_args...))". Such calls should leave string
interpolation to the logging method itself and be written "logging.<logging
method>(format_string, format_args...)" so that the program may avoid
incurring the cost of the interpolation in those cases in which no message
will be logged. For more, see http://www.python.org/dev/peps/pep-0282/. This
message belongs to the logging checker.
> pylint --help-msg W1202
No config file found, using default configuration
:logging-format-interpolation (W1202): …
```
=> MAINT: logging: remove manual interpolation

intelmq/lib/bot.py
When dumping to a file due to processing error, if the dump didnt exist yet, we got on stderr FileNotFound and that was all – nothing in logs, nothing nowhere.  
The correct behaviour is to create new file.
=> dump silently failed

intelmq/bots/BOTS, intelmq/bots/outputs/elasticsearch/README.md, intelmq/bots/outputs/elasticsearch/output.py
Elasticsearch doesn't provide authentication out of the box, the most common solution adopted during deployments is to publishing the service behind a reverse proxy.
This patch adds the option to authenticate to it using http basic authentication.
=> add http-basic authentication support to elasticsearch bot

intelmq/bots/parsers/bambenek/parser.py, intelmq/tests/bots/parsers/bambenek/test_parser.py
Adds malware name from the last column (url with file named after malware) in the csv.
=> [ENH] bambenek parser: add malware name from the url available in the feed

CHANGELOG.md, NEWS.md, intelmq/etc/defaults.conf, intelmq/lib/bot.py, intelmq/tests/lib/test_bot.py, intelmq/tests/lib/test_parser_bot.py
It's now configurable how often the "Processed .. messages" is logged. You can give a count and seconds.
See #743
=> Log count of processed messages configurable

docs/INSTALL.md
Removing the python3-typing as this is now installed as part of the standard library as of python 3.5, per:
https://docs.python.org/3/library/typing.html
Confirmed on system:
Linux ubuntu14-generic-template-01 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
>>> dir(typing)
['AbstractSet', 'Any', 'AnyMeta', 'AnyStr', 'AsyncIterable', 'AsyncIterator', 'Awaitable', 'BinaryIO', 'ByteString', 'CT', 'Callable', 'CallableMeta', 'Container', 'DefaultDict', 'Dict', 'Final', 'FrozenSet', 'Generator', 'Generic', 'GenericMeta', 'Hashable', 'IO', 'ItemsView', 'Iterable', 'Iterator', 'KT', …
=> Modify INSTALL.md remove Ubuntu 16 install instructions

docs/intelmqctl.md, intelmq/bin/intelmqctl.py, intelmq/lib/bot_debugger.py
(This is a continuation of PR #973 , because I completely messed up a git history...)
BotDebugger is called via intelmqctl. It starts a live running bot instance,
leverages logging to DEBUG level and permits even a non-skilled programmer
who may find themselves puzzled with Python nuances and server deployment twists
to see what's happening in the bot and where's the error.
Depending on the subcommand received, the class either
* starts the bot as is (default)
* processes single message, either injected or from default pipeline (process subcommand)
* reads the message from input pipeline or send a message to output pipeline (message subcommand)
Further help was added to argparse help of intelmqctl:
Possible commands:
```
intelmqctl run bot-id (bot.start())
intelmqctl run bot-id message …
```
=> Bot debugging

intelmq/bin/intelmqctl.py
We had an error – our proprietary bot wasn't listed in BOTS file. Thus, no launcher in bin was created. When launching whole botnet only bots that preceded this bot in the alphabet were launched, the rest stayed stopped.  
With this change, when an error occurs, the rest of the botnet will stay unaffected → only erroneous bots won't get launched → it will be easier to detect the bug for the administrator.
=> error in the bot shouldnt affect whole botnet

docs/README.md
For those who have already installed, a link to the user guide on the main page would likely be useful. Also link-ifying ToC within page and to other documents
=> Add Link to User Guide on main page

intelmq/bots/experts/cymru_whois/expert.py, intelmq/bots/parsers/alienvault/parser_otx.py, intelmq/tests/bots/experts/cymru_whois/test_expert.py, intelmq/tests/bots/parsers/alienvault/test_parser_otx.data, intelmq/tests/bots/parsers/alienvault/test_parser_otx.py
1. Ignore registry value "Other" from cymru. Provides a workaround #996 
2. Came across two types of timestamp for OTX feed
```
"modified": "2017-05-20T13:43:54"
"modified": "2017-05-20T13:43:28.563000"
```
I am not sure if this was one time system error or their lib strips sub-seconds part if it is perfect 0?
The check here fixes it only for modified time entry and other timestamps are left unchanged.  Test case for this is added as well.
=> [Fix] Two minor fixes

intelmq/bots/parsers/shadowserver/config.py
@cert-bund and @th-certbund have created a configuration for shadowservers accessible smb feed.
I've tested the config with yesterdays dataset for germany and it works well.
=> Adds config for Shadowserver Accessible SMB-Feed

intelmq/bots/parsers/shadowserver/config.py
As  described in 
* https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas
* https://stackoverflow.com/questions/11597901/why-does-python-allow-a-trailing-comma-in-list#11597911
it is cool to use trailing commas in lists, dicts and some other python types.
So we shall do so consistently. (This is branched off https://github.com/Intevation/intelmq/tree/dev-shadowserver-Accessible-SMB to allow accepting the other first.)
=> Dev shadowserver config codecleanness

docs/Bots.md
Extends the documentation of the generic csv parser.
=> [doc] Mention the extra-column in the docs of the generic csv parser

CHANGELOG.md, NEWS.md, docs/Bots.md, intelmq/bots/experts/ripencc_abuse_contact/expert.py, intelmq/lib/message.py, intelmq/lib/test.py, intelmq/tests/bots/experts/ripencc_abuse_contact/test_expert.py, intelmq/tests/lib/test_message.py
* can now optionally replace existing abuse contact
* split parameter `query_ripe_stat` into `query_ripe_stat_asn` and `query_ripe_stat_ip`
* better error handling
* lib/message: overwriting something with None now has the same behavior as adding sth with None:
if you overwrite an existing value with None/empty string, it will be deleted. Previously this did nothing.
* small fixes/additions in the tests library
and the test coverage of this bot is now 100% incl. all branches :)
=> Revised RIPE abuse contact expert, fix behavior of overwriting an event

intelmq/bots/experts/deduplicator/README.md, intelmq/bots/experts/deduplicator/expert.py, intelmq/tests/bots/experts/deduplicator/test_expert.py
Add boolean parameter `bypass`. If set the deduplicator will simply pass along the msgs bypassing deduplication mechanism. Useful in case you dont want to change the configuration but still want to bypass deduplicator temporarily.
=> [enh] bypss mechanism for deduplicator

CHANGELOG.md, intelmq/bin/intelmqctl.py
When running `intelmqctl run bot-id` and stopping/killing bot-id in parallel, this threw a FileNotFound exception. As we can't handle this in `bot_run` (It does not know who killed it), we need to implement this check in `bot_stop`.
=> BUG: ctl: handle already removed PID

CHANGELOG.md, intelmq/bin/intelmqctl.py, intelmq/lib/bot.py
Sigint can be captured by parent processes
fixes certtools/intelmq#981
fixes certtools/intelmq-manager#103
See also https://unix.stackexchange.com/questions/149741/why-is-sigint-not-propagated-to-child-process-when-sent-to-its-parent-process
=> Use SIGTERM to stop bots

intelmq/bots/experts/modify/examples/morefeeds.conf
Added modify expert rule for different "ramnit" malware names (like "ramnit-0xe371bf19") in Shadowserver Botnet Drone feed.
=> Added modify rule for ramnit

CHANGELOG.md, NEWS.md, intelmq/bin/intelmqctl.py, intelmq/lib/bot.py
fixes certtools/intelmq#1021
I am using `proc.status()` in `IntelMQProcessManager.bot_status` if possible to get a more accurate result. But that's only implemented for the start of a single bot now.
Looks like this now:
```
> intelmqctl start abusech-domain-parser 
intelmqctl: Starting abusech-domain-parser...
intelmqctl: abusech-domain-parser is stopped.
CRITICAL - Traceback (most recent call last):
File "/home/sebastian/dev/intelmq/intelmq/lib/bot.py", line 57, in __init__
self.__load_defaults_configuration()
File "/home/sebastian/dev/intelmq/intelmq/lib/bot.py", line 420, in __load_defaults_configuration
self.parameters.log_processed_messages_seconds = datetime.timedelta(seconds=self.parameters.log_processed_messages_seconds)
AttributeError: 'Parameters' object has no attribute …
```
=> Log bot's errors if failed to start and check for defaults.conf completeness

CHANGELOG.md
I think, the default value should be False (as seen in the code at https://github.com/certtools/intelmq/blob/master/intelmq/bots/experts/deduplicator/expert.py line 41)
=> deduplication bypass default

.travis.yml, debian/changelog, debian/conffiles, debian/control, debian/cron.d/intelmq-update-data, debian/intelmq.postinst, debian/intelmq.postrm, debian/intelmq.tmpfile, debian/patches/fix-dnspython-name.patch, debian/patches/fix-intelmq-paths.patch, debian/patches/series, debian/rules, debian/sedfile, debian/source/format, docs/INSTALL.md, intelmq/tests/lib/test_pipeline.py, setup.py
I used these modifications/files for all the recent release builds, so it's known to work.
The build packages use LSB paths only.
This branch contains cherry-picked changes from the dev-debian branch
The current 1.0.1-2 release in unstable repo is based on this branch
=> Packaging and LSB

CHANGELOG.md, docs/Developers-Guide.md, intelmq/bin/intelmqctl.py, intelmq/bots/experts/asn_lookup/expert.py, intelmq/bots/outputs/file/output.py, intelmq/lib/bot.py
Bots can specify a static method `check(parameters)` which can perform individual checks specific to the bot. These functions will be called by `intelmqctl check` if the bot is configured with the given parameters.
Needed for antoinet/intelmq#20 / https://github.com/certtools/intelmq/pull/1083#discussion-diff-136086094R146
=> Call bot check

CHANGELOG.md, NEWS.md, intelmq/bots/BOTS, intelmq/bots/experts/maxmind_geoip/expert.py, intelmq/lib/message.py, intelmq/tests/lib/test_message.py
Description from the changelog:
> - intelmq.lib.message.Message.add: The parameter overwrite accepts now three different values: True, False and None (new).
>   True: An existing value will be overwritten
>  False: An existing value will not be overwritten (previously and exception has been raised when the value was raised).
>   None (default): If the value exists an KeyExists Exception is thrown (previously the same as False).
>   This allows shorter code in the bots, as an 'overwrite' configuration parameter can be directly passed to the function.
You can then pass a given configuration parameter directly to the `add()` function, for example here shown for the maxmind expert.
=> lib/Message: overwrite parameter enhancement

CHANGELOG.md, NEWS.md, docs/Harmonization-fields.md, intelmq/bots/parsers/alienvault/parser_otx.py, intelmq/etc/harmonization.conf, intelmq/tests/bin/initdb.sql, intelmq/tests/bots/experts/ripencc_abuse_contact/test_expert.py, intelmq/tests/bots/parsers/alienvault/test_parser_otx.data, intelmq/tests/bots/parsers/alienvault/test_parser_otx.py
Bringing this from #1037 
This PR 
- adds hamonization type for urlpath as `source.urlpath` and `destination.urlpath`. A use case for this is to consume IoCs for HTTP/Web accessible shells and backdoors.
- fixes issues with URI handling in OTX feed where a URI can contain both a url like `http://test.com/x/y/z` or just path eg `/x/y/z`.
- test cases for above.
- adds `source.urlpath` and `destination.urlpath` in initdb.sq
- add information to changelog and news
- add information to upgrade db.
=> add urlpath harmonization type

CHANGELOG.md, intelmq/bots/collectors/mail/collector_mail_url.py
=> Mail URL collector: reconnect for marking as seen if necessary

docs/Bots.md, intelmq/bots/BOTS, intelmq/bots/outputs/postgresql/output.py, intelmq/lib/message.py, intelmq/tests/bots/outputs/postgresql/test_output.py, intelmq/tests/lib/test_message.py
* fixes certools/intelmq#1107
* introduced a new parameter jsondict_as_string for the postgresql output bot with a useful default
* new parameter jsondict_as_string for `Message.to_dict`
=> BUG: fix saving extra.* as string for postgres

intelmq/lib/message.py
Fixes the performance issues listed in bug #1117 . 
* Comment out `functools.lru_cache` decorator
* ~reorder the call to `_get_type_config` in `add`, and pass the result to `__is_valid_key` and `__is_valid_value` in params, so that these functions dont have to call `_get_type_config`~
This change will need lot of changes in tests, it has been undone.
=> Performance fix

CHANGELOG.md, intelmq/bots/parsers/shadowserver/README.md, intelmq/bots/parsers/shadowserver/config.py, intelmq/tests/bots/parsers/shadowserver/accessible-cisco-smart-install-reconstructed.csv, intelmq/tests/bots/parsers/shadowserver/accessible-cisco-smart-install.csv, intelmq/tests/bots/parsers/shadowserver/test_accessible_cisco_smart_install.py
Based on #1121 with added docs and tests
=> Shadowserver Accessible Cisco Smart Install with tests and docs

CHANGELOG.md, intelmq/bots/parsers/abusech/parser_ransomware.py, intelmq/bots/parsers/generic/parser_csv.py, intelmq/bots/parsers/phishtank/parser.py, intelmq/bots/parsers/shadowserver/parser.py, intelmq/bots/parsers/turris/parser.py, intelmq/lib/bot.py
=> bots: ignore NULL bytes in all csv parsers

intelmq/tests/bots/experts/cymru_whois/test_expert.py
```
AS      | IP                                       | BGP Prefix          | CC | Registry | Allocated  | AS Name
6939    | 2002:3ee0:3972:0001::1                   | 2002::/16           |    | other    |            | HURRICANE - Hurricane Electric, Inc., US
```
=> FIX: adapt cymru whois expert tests

intelmq/bots/outputs/restapi/output.py
This PR ads the option to log response texts while the bot runs in debug mode. This option might be helpful while debugging the interaction between intelmq and intelmq "consumer". 
Description: If the logging level of bot/intelmq is set to debug and response is not success (HTTP 200), the bot tries to log the response text.
=> Debug logging of response text for restapi bot

CHANGELOG.md, NEWS.md, docs/Harmonization-fields.md, intelmq/bots/experts/idea/expert.py, intelmq/bots/experts/taxonomy/expert.py, intelmq/bots/parsers/n6/parser_n6stomp.py, intelmq/lib/harmonization.py, intelmq/tests/bin/test_gen_harm_docs.py
fixes certtools/intelmq#738
mappings for idea are confirmed by @pharook
=> fix type mapping for n6 parser

CHANGELOG.md, intelmq/lib/bot.py, intelmq/lib/pipeline.py
reported as https://lists.cert.at/pipermail/intelmq-users/2017-December/000022.html
=> stop for redis "OOM command not allowed when used memory > 'maxmemory'."

intelmq/bin/intelmqctl.py, intelmq/lib/bot.py
the default run_mode is called continuous according to docs, in lib/bot it was stream
and add a check for this parameter in ctl check
=> small run_mode fixes and checks

CHANGELOG.md, docs/intelmqctl.md, intelmq/bin/intelmqctl.py
intelmqctl now exits with exit codes > 0 when errors happened or the operation was not successful. Also, the status operation exits with 1, if bots are stopped, but enabled. (fixes #977)
=> BUG: ctl: proper exit codes

intelmq/bots/parsers/cleanmx/parser.py
I added self.logger.info to check the content of `events` variable and found this:
```
2018-01-18 17:32:58,916 - cleanmx-phishing-parser - INFO - Bot is starting.
2018-01-18 17:32:58,918 - cleanmx-phishing-parser - INFO - Pipeline ready.
2018-01-18 17:33:05,354 - cleanmx-phishing-parser - INFO - ['source.abuse_contact', 'extra', 'raw', 'feed.url', 'time.observation', 'source.url', 'source.geolocation.cc', 'source.registry', 'source.ip', 'source.fqdn', 'classification.type', 'feed.provider', 'status', 'feed.name', 'feed.accuracy']
2018-01-18 17:33:05,581 - cleanmx-phishing-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
File "/intelmq/intelmq/lib/bot.py", line 144, in start
self.process()
File "/intelmq/intelmq/lib/bot.py", line 622, in process …
```
=> CleanMX Fix

.travis.yml
* Puts popd on a line of its own, otherwise its return value will
override the exit code of the dpkg-buildpackage command, causing a
successful build, even with it failed.
=> Improves travis setup.

.travis.yml, CHANGELOG.md, debian/patches/fix-intelmq-paths.patch
Separate build for debian package and codestyle
Only the steps which are needed for the current build are executed
-> saves time and easier to see which step failed
obsoletes/includes #1168
=> Rework travis setup and fix debian package build

intelmq/lib/bot.py
The only "small" reason for the additional line is just to help users on the same problem as I had which is:
A parser bot is processing thousands of lines and in the middle of the process, parser found one line with an error and automatically wrote a log message about it but continued. In the end, after all thousand lines processed, the log file is full of messages saying `INFO - Processed 500 messages since last logging.` and in the end has an additional log message saying `INFO - Dumping message from pipeline to dump file.`. 
In my perspective, before the log line `INFO - Dumping message from pipeline to dump file.`, bot should write another log line mentioning the issue with the specific message that is about to dump in order to alert the user that need to check all log file looking …
=> Extra log line during dumping message process

CHANGELOG.md, intelmq/lib/bot.py
don't initialize source pipeline if not necessary
always raise PipelineError in case of connection issues
always stop in these cases, do never pass, would only result in loops
=> BUG: lib/bot: enhance pipeline error handling

NEWS.md, intelmq/bots/parsers/shadowserver/config.py
Rename identifiers:
Make SSL-POODLE/SSL-FREAK lowercase like all other identifiers.
Rename open-netbios to open-netbios-nameservice as this report only deals with 137/udp, not netbios in general.
=> Shadowserver config.py netbios, poodle, freak

intelmq/bots/experts/sieve/README.md, intelmq/bots/experts/sieve/expert.py, intelmq/tests/bots/experts/sieve/test_expert.py, intelmq/tests/bots/experts/sieve/test_sieve_files/test_network_host_bits_list_match.sieve
I found it handy to have a parameter for setting strict=False when creating an IP network. If strict=True, we get ValueError: XY has host bits set.
=> Sieve strictness (allow ip networks with hosts bits set)

CHANGELOG.md, intelmq/bots/experts/sieve/README.md, intelmq/bots/experts/sieve/expert.py, intelmq/bots/experts/sieve/sieve.tx, intelmq/tests/bots/experts/sieve/test_expert.py, intelmq/tests/bots/experts/sieve/test_sieve_files/test_named_queues.sieve
Sieve bot now can distribute events to appropriate named queue by an optional parameter next to word 'keep'
@antoinet @wagner-certat 
PS: Note that the error in travis-ci/pr seems to have nothing common with my changes.
=> Fixes #1207 Sieve bot named queues ( #1088 ) usage

CHANGELOG.md, intelmq/bin/intelmqctl.py
Both start and stop command returned tuple (exit-status, string). Restart command returned ((exit-status-of-stop, string-of-stop), (exit-status-of-start, string-of-start)). Since exit-status was a tuple instead of a number, in the terminal error pipe received that tuple. Since intelmq-manager read only output-pipe, it wasn't aware of this incorrect behaviour. With my another pull request, intelmq-manager now handles error-pipe too, so that restart command stopped working.
Old wrong behaviour:
```bash
www-data@jezevec:~$ PATH=~/.local/bin intelmqctl restart abuse-ch-feodo-tracker-domains-parser
intelmqctl: abuse-ch-feodo-tracker-domains-parser was NOT RUNNING.
intelmqctl: Starting abuse-ch-feodo-tracker-domains-parser...
intelmqctl: abuse-ch-feodo-tracker-domains-parser is running.
(0, …
```
=> Return value of restart command

CHANGELOG.md, intelmq/bin/intelmqctl.py
no non-json information about wrong bots are output because that would confuse eg. intelmq-manager
For example, if there was defined a bot that didnt exist in BOTS, a superfluous line was printed:
```bash
IntelMQ-Collector stopped <-- superfluous line!
{"restapi-output": "disabled", "IntelMQ-Collector": "stopped", "JSON-Parser": "running", "TCP-Output": "stopped", "abuse-ch-feodo-tracker-domains-collector": "running", "abuse-ch-feodo-tracker-domains-parser": "running", "abuse-ch-feodo-tracker-ips-collector": "running", "abuse-ch-feodo-tracker-ips-parser": "running", "abuse-ch-zeus-tracker-domains-collector": "running", "abuse-ch-zeus-tracker-domains-parser": "running", "abuse-ch-zeus-tracker-ips-collector": "running", "abuse-ch-zeus-tracker-ips-parser": "running", "abusix-expert-cz": …
```
=> intelmqctl start botnet --type json fix

CHANGELOG.md, docs/intelmqctl.md, intelmq/bin/intelmqctl.py, intelmq/lib/bot_debugger.py
fixes certtools/intelmq#1075
introduces new loglevel parameter
=> BUG/ENH: ctl run: log level handling

intelmq/bots/parsers/shadowserver/config.py
Both functions convert_hostname_and_url() and convert_httphost_and_url() were broken or incomplete. Replaced by new function convert_http_host_and_url().
=> Fix Shadowserver parser convert_http_host_and_url

CHANGELOG.md, intelmq/bin/intelmqctl.py, intelmq/lib/pipeline.py, intelmq/lib/utils.py
Queue path names were incorrectly listed amongst standard queue names. Named queue got displayed twice – as a standard queue and as a named path. Note that this information didn't serve anything because multiple queues may have the same name, ex: _default. Plus, manager got confused, having no way to distinguinsh path names from standard queue names.
> intelmqctl list queues
intelmqctl: _default - 0
intelmqctl: abuse-ch-feodo-tracker-domains-parser-queue - 0
=> Fix: don't display named paths amongst standard queues.

intelmq/bots/parsers/misp/parser.py
Hi,
just recognized the current parser simply ignores MISP Attributes if they are nested into an MISP Object.
Would like to see this minor code change go upstream since many misp sharing instances are using objects to group attributes together.
Regards,
Hendrik
=> MISP Parser to recognize attribtes nested in objects

contrib/feeds-config-generator/README.md, contrib/feeds-config-generator/intelmq_gen_feeds_conf, docs/Feeds.md, intelmq/bin/intelmq_gen_docs.py, intelmq/bots/BOTS, intelmq/etc/feeds.yaml, intelmq/etc/runtime.conf, intelmq/lib/bot.py
=> Name and Provider fields cleaning

intelmq/bots/parsers/cleanmx/parser.py, intelmq/tests/bots/parsers/cleanmx/test_parser.py
Previously time.source was appearing empty. That caused
issues for upstream parsing via Logstash.
Patch reads the epoch time from the CleanMX 'first' field then
assigns to time.source. Also adds field tests to the existing
parser tests.
=> Fix #1329, CleanMX parser support for 'first' source timestamp field

intelmq/etc/defaults.conf
This value is used here without this typo:
https://github.com/certtools/intelmq/blob/develop/intelmq/bin/intelmqctl.py#L469
=> Fixed typo in defaults.conf key

intelmq/bots/experts/maxmind_geoip/expert.py
MaxMind provides different country attributes for an IP:
- country: Country where MaxMind _believes_ the user is located.
- registered_country: Country registered with the network range.
Incidents are usually reported to the network owner responsible for the affected IP or the respective national CSIRT. So in particular for CDN networks or satellite providers, we are not interested in the country a user is (potentially) located but in the location of the network owner.
Example for DE vs. US:
```
network:IP-Network:38.87.230.0/23
network:Org-Name:Interlax Telecom
network:Street-Address:50 NE 9th St.
network:City:Miami
network:State:FL
network:Country:US
```
Maxmind results:
```
country: DE
registered_country: US
```
Example for DE vs. AF:
```
inetnum:        180.222.136.0 - 180.222.143.0 …
```
=> Maxmind: Use registered_country instead of country

CHANGELOG.md, docs/Bots.md, intelmq/bots/collectors/http/collector_http.py
Generic URL fetcher used local time only. But my feed generates always generates yesterday's data. So I needed to fetch yesterday.
`http_url_formatting` previously could be `true` to turn on time formatting. Now, it can contain a JSON that is passed to timedelta function so that one can easily do the relative date shift.
=> collector http time-delta ability

intelmq/lib/bot.py
Do not create `tmp_msg` variable when debug logging is not enabled
=> Bot.receive_message small optimisation

docs/Feeds.md, intelmq/etc/feeds.yaml
Following the discussion in https://github.com/certtools/intelmq/pull/1378, here's the documentation for the Abuse.ch URLhaus feed for malicious URLs. Please note that this configuration is targeted at the CSV Feeds provided for specific ASNs, country codes or top level domains as described here: https://urlhaus.abuse.ch/feeds/
The config mentioned by @navtej in https://github.com/certtools/intelmq/pull/1378#issuecomment-463500234 corresponds to the CSV format for the entire URLhaus dump, which is probably not suitable to pull as feed (https://urlhaus.abuse.ch/downloads/csv/).
=> Added documentation for abuse.ch URLhaus feed

intelmq/bots/BOTS, intelmq/bots/outputs/redis/README.md, intelmq/bots/outputs/redis/output.py, intelmq/tests/bots/outputs/redis/test_output_as_hierarchical_json.py
Current style of output is kept as default and send_as_hierarchical_json isn't a required field.
=> Added support for hierarchical json output for redis output bot

intelmq/bots/parsers/netlab_360/parser.py
In our intelmq instance the parser was raising IndexErrors for DGA feed. The empty blank line separating comments from data could include multiple blank characters and therefore raising an IndexError. This was caused by checking the length of string and not stripping it from blank character prefixes and suffixes.
We couldn't target the main cause yet, but this could affect the parsing process.
=> Ignore any lines starting with blank characters in netlab 360 parser

intelmq/lib/bot.py
Mentioning keyword 'error' in this way presents problems when greping for real error messages
=> Remove keyword 'error' from log message associated with non ERROR state

intelmq/bots/parsers/dataplane/parser.py
Introduce feed field count checking before list elements access.
We have experienced IndexErrors with this parser, but couldn't locate the source of the problem regarding feed formats. These changes should be sufficient enough for tracing back the source and deals with IndexErrors.
=> Dataplane parser refactoring

intelmq/bots/parsers/shadowserver/config.py
Remove storing fixed 'tag' values in extra. Fix classification.identifier for ftp.
=> Shadowserver parser: No fixed 'tag' values in extra, fix identifier for ftp.

docs/Bots.md, intelmq/bots/BOTS, intelmq/bots/outputs/elasticsearch/README.md, intelmq/bots/outputs/elasticsearch/output.py
Adds SSL for connection to Elasticsearch. Includes:
- new parameters for using + verifying SSL, optional path to CA cert bundle, option to suppress warnings
- docs
Client authentication is not implemented -- I left placeholders in the ES client code but don't have a setup right now using client certs to test the behavior. It may just need two more parameters added to the bot.
Related to #1150
=> Elasticsearch SSL Support

docs/Bots.md, intelmq/bots/outputs/mongodb/REQUIREMENTS.txt, intelmq/bots/outputs/mongodb/output.py
Hi,
I've tried to update package `pymongo` to 3.0.0 because of issue #1063 
To run local mongo:
`$ docker run -i -t --network host mongo:3.4-xenial /bin/bash`
To run tests:
`$ INTELMQ_TEST_DATABASES=1 python intelmq/tests/bots/outputs/mongodb/test_output.py`
To review my changes I used this [changelog](https://github.com/mongodb/mongo-python-driver/blob/0b0f045d56176807edea9e547ab6a1288740a5d8/doc/changelog.rst#changes-in-version-30)
=> Update `pymongo` to 3.0.0 version

intelmq/bin/intelmqctl.py
Hi! I'm keen to try out IntelMQ but ran into an error straight after installation. Here's a simple fix.
This error occurs when invoking `intelmqctl` on my plain Ubuntu 18.04 LTS install (vagrant, ubuntu/bionic64, dependencies installed as per the install guide):
>UnboundLocalError: local variable 'logging_level_stream' referenced before assignment
The pull request simply sets that to DEBUG, allowing intelmqctl to run. Not exhaustively tested. I tried running the tests in the repo but 26 of them failed, perhaps because of Vagrant? This pull request doesn't change the test results, anyway.
=> Set logging_level_stream when defaults are unavailable

intelmq/bots/BOTS, intelmq/bots/experts/cymru_whois/expert.py, intelmq/bots/experts/reverse_dns/expert.py, intelmq/tests/bots/experts/cymru_whois/test_expert.py, intelmq/tests/bots/experts/reverse_dns/test_expert.py
Fixes https://github.com/certtools/intelmq/issues/1452
Default overwrite is set to true.
=> ENH: default overwrite on reverse_dns and cymru_whois

intelmq/bin/intelmqctl.py
`MESSAGES` dict of intelmqctl.py doesn't include `restarting` key, so `intelmqctl restart` fails when it tries to log. This PR fixes it.
```
Traceback (most recent call last):
File "/bin/intelmqctl", line 11, in <module>
load_entry_point('intelmq==2.1.0', 'console_scripts', 'intelmqctl')()
File "/usr/lib/python3.6/site-packages/intelmq/bin/intelmqctl.py", line 1732, in main
return x.run()
File "/usr/lib/python3.6/site-packages/intelmq/bin/intelmqctl.py", line 956, in run
retval, results = args.func(**args_dict)
File "/usr/lib/python3.6/site-packages/intelmq/bin/intelmqctl.py", line 999, in bot_restart
return self.botnet_restart(group=group)
File "/usr/lib/python3.6/site-packages/intelmq/bin/intelmqctl.py", line 1112, in botnet_restart
log_botnet_message('restarting')
File …
```
=> BUG: fix botnet restart logging message

intelmq/bin/intelmq_generate_misp_objects_templates.py
Also supports updating an existing template.
=> new: script to generate MISP Objects templates

intelmq/bin/intelmqctl.py
* Extend the filename for logging in the same way as lib/utils.py .
=> Fix usage description for intelmqctl

intelmq/bots/experts/reverse_dns/expert.py
Hi, I've found this hidden bug. There was no effect thanks to `harmonisation.py/import dns.resolver`, if you comment this line, the unit test fails.
See:
```python3
import dns
dns.resolver, dns.reversename, dns.exception.DNSException # AttributeError: module 'dns' has no attribute 'resolver'
```
```python3
import dns.resolver
dns.resolver, dns.reversename, dns.exception.DNSException # no problem
```
=> hidden bug

intelmq/bots/collectors/microsoft/REQUIREMENTS.txt
Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
see https://github.com/certtools/intelmq/issues/1530
=> Update Microsoft Collector REQUIREMENTS.txt

README.rst
* remove toc for developers-guide as the section is gone and now part of how to participate
=> DOC: remove old toc entry from README.rst

intelmq/bots/collectors/misp/collector.py
The misp 'Event' object key must be accessed.
=> add missing misp event key

docs/Feeds.md, intelmq/etc/feeds.yaml
Fixes #1571.
I kept the `type_translation` even tho the feed always (as far as I can say) sets `Threat` column to `malware_download` (I found very few occasions where the `Threat` column was empty). If there ever appears any other `Threat` value, it will be ignored (the feed documentation doesn't list them therefore we can not map them before they appear and so far it seems very unlikely anyway).
=> FIX: feed revision: Abuse.ch URLhaus

intelmq/bots/BOTS, intelmq/bots/parsers/eset/parser.py
Occasionally, `@ipv4_NXDOMAIN` (and presumably the same with ipv6) may pop up in place of an IP or null in the `ip` field. This is a simple workaround to still add those entries.
Also, a recover_line won't hurt.
=> ESET parser: workaround NXDOMAIN in place of IP, add recover_line

intelmq/bots/parsers/malwareurl/parser.py
Some alerts from malwareurl.com contain IP address in the Domain column.  Adding IP address value into source.fqdn field results in error.
=> BUG: parser fails when IP address comes in the domain column

CHANGELOG.md, docs/intelmqctl.md, intelmq/bin/intelmqctl.py
- Adds the `--sum`, `--count` and `-s` flag for `intelmqctl list queues`, which shows the sum of events of all queues
- Updates the corresponding _intelmqctl_ documentation
- Updates CHANGELOG.md
=> intelmq list queues: --sum flag for showing total count Fixes #1408

intelmq/bots/parsers/danger_rulez/parser.py
Define variables before referencing
add the same behavior to all dynamic fields i.e. timestamp and ip.
=> BUG: danger rulez parser: correctly skip malformed rows

intelmq/lib/bot.py
This is a tiny change to make `parameters` key optional for bot runtime configuration. Some bots do not require any specific parameters. With this PR it is no longer necessary to have empty `"parameters": {}` inside `runtime.conf` and therefore it reduces configuration size.
Before this PR the intelmq would raise KeyError exception when `parameters` is omitted from the configuration.
=> ENH: makes bot parameters optional

CHANGELOG.md, NEWS.md, intelmq/bots/experts/cymru_whois/expert.py
The cache key calculation has been fixed. It previously led to duplicate keys for different IP addresses and therefore wrong results in rare cases. The cache key calculation is intentionally not backwards-compatible. Therefore, this bot may take longer processing events than usual after applying this update.
fixes certtools/intelmq#1592
=> BUG: fix cymru expert cache key calculation

docs/Feeds.md, intelmq/etc/feeds.yaml
* Changes the feed provider name to it's true author.
* Changes feed url to csv file with shadowserver-like syntax (it includes more information).
* This allows using generic csv parser, therefore `intelmq.bots.parsers.dyn.parser` could be deprecated.
=> FIX: feed revision: DynDNS Infected Domains

intelmq/lib/bot.py, intelmq/lib/utils.py
The purpose of this PR is to add the support for log rotation to the intelmq. The need for this is, at least in my case, for log running deployments typically in Docker. Since the processing info logs can take a large portion of disk space this feature could be used as a solution. I'm well aware that the amount of logs could be reduced by restricting the log level to warning of error but this solution is in my opinion better since it allows for a greater control over disk usage and keeping the info logs, which might still hold some value for troubleshooting.
To enable rotation of logs I've added two parameters _logging_max_size_ and _logging_max_copies_ which directly map to the values for limiting the sizes of logs and backup counts from Python's …
=> Rotating file handler added as another logging option

docs/user/FAQ.rst, docs/user/bots.rst, docs/user/configuration-management.rst, docs/user/upgrade.rst
* Fixing some internal links that were still using markdown syntax
* Adjusting some preformatted text to RST syntax
* Readjusting some of the sections and chapters to make internal
references (using :ref:) easier possible
=> DOC: improvements

docs/user/bots.rst, intelmq/bots/BOTS, intelmq/bots/experts/splunk_saved_search/expert.py
An expert bot that enriches events based on Splunk saved searches.
=> Splunk saved search expert bot

intelmq/bin/intelmqctl.py
The `bd` variable has to be instantiated with the BogDebugger object
to be usable.
=> BUG: use BotDebugger object

intelmq/bin/intelmqctl.py
As already mentioned in https://github.com/certtools/intelmq/issues/1675 there might be a possible misbehaviour. To solve this issue, we can check if they enviroment variable is set.
=> [FIX] Issue 1675

CHANGELOG.md, NEWS.md, docs/user/bots.rst, intelmq/bots/collectors/xmpp/collector.py, intelmq/bots/outputs/xmpp/output.py
Both the XMPP output bot as well as the XMPP collector bot require
the `sleekxmpp` library which is deprecated. It would be possible to
modify the bots to use the successor `slixmpp` library, but a short
survey
https://lists.cert.at/pipermail/intelmq-users/2020-October/000177.html
did not bring up anyone using the bots, so they are being marked as
deprecated for now and will be removed in version 3.0.
=> Deprecate the XMPP bots

debian/changelog, debian/control, debian/py3dist-overrides, debian/rules
d/changelog:
* Fix bogus-mail-host-in-debian-changelog
https://lintian.debian.org/tags/bogus-mail-host-in-debian-changelog.html
* Fix depends-on-essential-package-without-using-version
This referres to `debianutils`. See
https://lintian.debian.org/tags/build-depends-on-essential-package-without-using-version.html
"The only reason to list an explicit dependency on an essential package
is if you need a particular version of that package"
* Fix: description-starts-with-package-name
https://lintian.debian.org/tags/description-starts-with-package-name.html
This also adds a synopsis, because according to policy, a Debian
package description consists 'of two parts, the synopsis or the
short description, and the long description'
* Fix: syntax-error-in-debian-changelog
There was a changed-by line …
=> A couple of bug fixes and updates of the Debian package

.github/pull_request_template.md
The pull request template points first and foremost to the developers
guide.
It also explains some quality characteristics we value in pull requests
and commit messages and points contributors to some external howtos.
See also
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates#pull-request-templates
=> Add a github pull request template

.gitignore, docs/autogen.py, docs/conf.py, docs/index.rst, docs/requirements.txt, intelmq/etc/harmonization.conf
The script `docs/autogen.py` still generated the harmonization field
overview as markdown file. To get rid of the recommonmark dependency,
the script now generates restructured text, like all the other
documentaiton source files.
This commit modifies the autogen.py file as described, it changes the
extension of the autogenerated file in .gitignore; it removes all traces
of recommonmark configs in the sphinx configuration files docs/conf.py.
It changes the inclusion of the autogenerated file in the documentation
index.rst file.
The commit also drops the doc/dev/IntelMQ-3.0-Architecture.md file from
the documentation- this is an internal WIP file and does not need to be
part of the user facing docs.
TODO: there are some field descriptions containing markdown syntax, they
should be updated.
=> Adapt doc buildsystem to only produce restructured text

.github/workflows/codespell.excludelines, setup.cfg
Given that we have to document some spelling mistakes made in the past,
we have to make codespell ignore those lines. This adds a
.github/workflows/codespell.excludelines file, that lists the exact
lines that sould be ignored by codespell, and adds the relevant setting
to the setup.cfg
=> Tell codespell to ignore specific lines

docs/user/bots.rst, intelmq/bots/experts/sieve/expert.py, intelmq/bots/experts/sieve/sieve.tx, intelmq/tests/bots/experts/sieve/test_expert.py, intelmq/tests/bots/experts/sieve/test_sieve_files/test_basic_math.sieve
Added possibility to use super basic math ( + and - operations ).
Sieve is now able to calculate a new datetime.
There should be no breaking change!
Usage:
```
add! time.observation += '1 hour'
add! time.observation -= '2 hours'
add time.observation += '1 hour'
add time.observation -= '2 hours'
update time.observation += '1 hour'
update time.observation -= '1 hour'
```
Closes #1680
=> [ENH] Sieve datetime operations

debian/control
dh-systemd is a transitional package that is not needed anymore and
leads to dependency errors on bullseye.
=> PKG: drop the dh-systemd dependency from the package

.github/workflows/debian-package.yml, .github/workflows/scripts/debian-package.sh, .travis.yml, debian/control
The workflow builds debian packages on Debian buster and bullseye. The
action runs on push & pull request events.
Artifacts are stored for 5 days, but only created for push events.
=> MAINT: Add a workflow that builds Debian packages

intelmq/bots/experts/sieve/expert.py, intelmq/lib/harmonization.py
Timezone was not interpreted correctly. Now we localize time to UTC in sieve expert.
=> Fixes sieve timezone "utc" & sieve variable bug

docs/user/intelmq-api.rst
intelmq-api does not serve static files anymore, that should be done by
a real webserver and is described in the intelmq-manager documentation.
=> DOC: update intelmq-api documentation

intelmq/tests/bots/collectors/rsync/test_collector.py
Currently this test will fail and throw an exception if rsync is not installed. So we should check first if rsync is installed, before running this test.
=> [FIX] Unittest checks if rsync is installed

intelmq/bots/parsers/shadowserver/config.py, intelmq/tests/bots/parsers/shadowserver/test_blocklist.py, intelmq/tests/bots/parsers/shadowserver/testdata/blocklist.csv
ShadowServer parses not CIDR notation networks correctly.
#Fixes 1720
=> Shadowserver Block List Feed: Parse CIDR-notation entries correctly

intelmq/tests/bots/experts/cymru_whois/test_expert.py
CrymuWhoisExportBot checks now ns1.univie.ac.at, which
hopefully will not be changed in near future.
=> [FIX] CrymuExport now checks ns1.univie.ac.at

intelmq/bots/collectors/alienvault_otx/COPYRIGHT.md
The OTXv2.py file is not shipped with IntelMQ anymore, therefore its
copyright file should not be part of IntelMQ, too.
=> MAINT: drop unused copyright file

intelmq/bots/collectors/mail/collector_mail_body.py
Sometimes we receive email reports like `this is happening right now` and there is no date/time included. So if we process emails once per hour - we don't have info about event time. Additional field `extra.email_received` in the mail body collector would help.
=> Insert date when email was received

CHANGELOG.md, docs/user/bots.rst, intelmq/bots/collectors/http/collector_http_stream.py, intelmq/bots/collectors/shodan/collector_stream.py
HTTP Stream collector should not raise a exception. Now we're able to define a threshold via `error_max_retries` as parameter.
**NOTE** This is a very "hacky" solution. Currently investigating the cause of this errors.
Closes #1435
=> [FIX] HTTP Stream Collector better error handling

CHANGELOG.md, intelmq/bots/collectors/twitter/collector_twitter.py
- Proper input validation in URLs using urllib. CWE-20, found by GitHub's CodeQL.
- Limit replacement ("pastebin.com", "pastebin.com/raw") to a maximum of one.
@hugeox (original author/maintainer) please review as well
=> BUG: twitter collector: proper URL parsing

CHANGELOG.md, docs/user/bots.rst, intelmq/bots/outputs/smtp/output.py, intelmq/tests/bots/outputs/smtp/test_output.py
Tests and SMTP OutputBot is now able to send to multiple recipients.
Thanks to @xfors
Fixes #1759
=> [FIX] SMTP Output can now send to multiple recipients

intelmq/bots/experts/ripe/expert.py
very minor fix
after the automatic conversion of self.parameters -> self, the member
__mode is obsolete and the same as mode.
=> MAINT: ripe expert: fix mode parameter usage

intelmq/lib/bot.py, intelmq/lib/exceptions.py, intelmq/lib/message.py, intelmq/tests/lib/test_bot.py
This fixes #1765.
It adds dump object to InvalidValue exception so that the code below has some meaningful data to dump and can just move on (the last two lines that acknowledge the message if there is a message to dump).
https://github.com/certtools/intelmq/blob/b7ba19ceaba219e6aa87a37784164dbdf0b3e680/intelmq/lib/bot.py#L372-L384
=> FIX: Adds somewhat dirty fix for #1765.

CHANGELOG.md, docs/index.rst, docs/user/FAQ.rst, docs/user/bots.rst, docs/user/configuration-management.rst, docs/user/intelmq-api.rst, docs/user/introduction.rst, intelmq/lib/bot.py
Adds a (longer) FAQ section to the API docs and links it from the generic FAQ page
minor changes and spelling fixes
bots: drop mention of obsolete and removed contrib/cron-jobs/update-geoip-data script
index: make new section for connections to other systems, reducing the long list of pages under the "User guide" section
=> Docs: FAQ for API and some minor fixes

.github/workflows/nosetests.yml
because for the full tests, it is already run during the setup-full.sh
script run.
=> Run the installation step only for the base tests

intelmq/lib/bot.py, intelmq/lib/pipeline.py
The `pipeline_args` argument of the pipeline factory should contain a
dict with the relevant attributes and their values instead of simply a
list containing the keys of the attributes.
Also the method itself has to get the values from the dict.
@schacht-certat  slaps @schacht-certat  around with a large trout.
=> FIX: the pipeline factory expects a dict, not simply a list

intelmq/lib/bot.py, intelmq/lib/test.py
the pipeline arguments are extracted from `self` by iterating over the
attributes, using dir(). But dir only returns the name of the variable,
not the value. Therefore, the check for ismethod needs to be done using
getattr, not the variable name.
=> BUG: lib/bot and lib/test: fix pipeline parameter check

CHANGELOG.md, intelmq/bots/parsers/cymru/parser_cap_program.py, intelmq/tests/bots/parsers/cymru/certname_20190327.txt, intelmq/tests/bots/parsers/cymru/test_cap_program_new.py
Previously, the bruteforce events only had the protocol in the comment, while most other categories had a (more or less) clear type-value syntax. Now, the bruteforce categories also uses the type-value syntax. That makes the parser a bit more bloated, as it needs to support both formats, the old and the new. Whereas I don't even know if this is a real switch, or just an additional format.
Interestingly the data no longer contains the application protocol (SSH in the case of the example) :/
fixes #1794
@aleksejsv
=> Cymru CAP Parser: Adapt to new format of 'bruteforce' category

CHANGELOG.md, docs/user/bots.rst, intelmq/bots/BOTS, intelmq/bots/experts/http/expert_status.py, intelmq/tests/bots/experts/http/test_expert_status.py
This adds the module
intelmq.bots.experts.http_status.expert.HttpStatusExpertBot
It also adds a description in the documentation and a changelog entry
introducing the new bot.
=> ENH: add http status code expert

CHANGELOG.md, docs/user/FAQ.rst
socket permission 777 are not necessary, use only 770 plus group
membership
=> docs: faq redis socket: less permissions

docs/user/intelmq-api.rst, docs/user/intelmq-manager.rst
Make the installation steps much more verbose and clear
- Split into deb/rpm packages and pip
- explain all steps in detail for the pip-installation
- add missing information, like positions.
- api: link to permissions section
- use the same structure for both pages
=> DOC: Enhance API and Manager documentation

CHANGELOG.md, debian/rules, intelmq/bin/intelmqsetup.py
fixes the paths for intelmq-api, as the intelmq-api always uses
/etc/intelmq and not CONFIG_DIR
Extends the functionality of intelmqsetup to set-up the webserver
configuration for the api and manager in a permissive way (if a part
fails, the program does not exit).
=> intelmqsetup: fix api directories, setup webserver

CHANGELOG.md, docs/user/bots.rst, intelmq/bots/BOTS, intelmq/bots/experts/http/expert_content.py, intelmq/tests/bots/experts/http/test_expert_content.py
This adds the module
intelmq.bots.experts.http.expert_content.HttpContentExpertBot and some
unit tests for the module.
It also adds a description in the documentation and a changelog entry
introducing the new bot.
=> ENH: add http content expert

CHANGELOG.md, intelmq/lib/pipeline.py
Check virtual host when retrieving queue sizes. Fixes output of `intelmqctl check` for orphaned queues if AMQP is used and the AMQP user has access to more virtual hosts
certtools/intelmq#1746
=> BUG: lib/pipeline: Ampq._get_qeues: ignore wrong vhost

CHANGELOG.md, intelmq/tests/lib/test_harmonization.py
This test fails if any other timezone than UTC is in use and causes
frequent but unnessary test fails.
So we can just skip it, if UTC is not in use on the system.
=> BUG TST: test_datetime_convert: skip if not UTC

CHANGELOG.md, intelmq/bots/collectors/shadowserver/collector_reports_api.py, intelmq/tests/bots/collectors/shadowserver/test_collector_reports_api.py
Added debug logging to show number of downloaded reports and download size
partly addresses #1688 and #1823
=> shadowserver collector: more debug logging

.github/workflows/debian-package.yml
The github action virtual environment pulls a new buildah version that is not configured correctly, therefore for now using the older ubuntu-18.04 virtual environment, unitl https://github.com/actions/virtual-environments/issues/3080 is fixed
=> MAINT: workaround for new buildah release

intelmq/bots/outputs/misp/output_api.py
with the new bot-level default values for parameters, the check function
needs to be adapted and not all parameters need to be given now
explicitly.
=> ENH: misp api output: update check function

CHANGELOG.md, intelmq/bots/experts/modify/examples/default.conf
if the malware name indicates a c2 server, but type is wrong, set the
type accordingly
when merged into develop, c2server needs to be changed to c2-server
=> ENH: modify example configuration: add c2 malware rule

intelmq/bin/intelmqctl.py
This fix introduces a _configured_bots_list method that is there to list
all bots that are configured in the runtime and removes the 'global'
entry from the bot list. This method is used in the botnet_start,
botnet_stop and the list_all_bots method.
=> FIX: remove the 'global' entry from the list of bots

CHANGELOG.md
The bug was both introduced and fixed in the development branch, so
there is no need to clutter the changelog with that information.
(A better place for the information would have been the commit message)
=> DOC: no need to mention development internal fixes in changelog

docs/user/bots.rst, docs/user/configuration-management.rst
The default format for the runtime configuration file will be yaml, so
the documentation should reflect that in all the code examples.
=> DOC: update the documentation to reflect the change to yaml

CHANGELOG.md, intelmq/bots/experts/gethostbyname/expert.py, intelmq/tests/bots/experts/gethostbyname/test_expert.py
the value null for the parameter gaierrors_to_ignore raised an error
this commit fixes this by handling it gracefully. actually was already
there, just in the wrong order
fixes certtools/intelmq#1886
=> BUG: gethostbyname: fix handling null gaierrors_to_ignore

intelmq/bin/intelmqctl.py
Those used to be part of the defaults.conf which is now gone.
Closes #1889
=> FIX: set defaults values for the logging handler

intelmq/lib/utils.py
Expert bot names wrong exported. Should now be fixed.
Fixes #1847
=> FIX: intelmqctl list bots now Output correct ExpertBot names

CHANGELOG.md, intelmq/__init__.py, intelmq/bin/intelmqsetup.py
sets ownership of var/lib and var/lib/state.json to intelmq
that should also fix the tests fail
handle errors moving the intelmq-manager directory more gracefully, so
that the program can continue and exit
=> BUG: fix intelmqsetup issues

docs/user/bots.rst, intelmq/bots/experts/sieve/expert.py, intelmq/bots/experts/sieve/sieve.tx, intelmq/tests/bots/experts/sieve/test_expert.py, intelmq/tests/bots/experts/sieve/test_sieve_files/test_append.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_bool_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_force_append.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_equals_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_overlaps_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_setequals_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_subsetof_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_supersetof_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_typed_values.sieve
This PR refactors some of the Sieve expert and extends the Sieve DSL. In particular, it adds:
* for the below items, a generic `TypedValue` type was added, which can be any of a float, int, bool or str, as well as `ListValue`, which can contain any of the above
* some methods of operating on list objects, like `:equals` for exact matching of lists, and `:setequals`, `:overlaps`, `:subsetof` and `:supersetof` for set-based operations, along with negated counterparts if `!` is specified before the operator (i.e `! :overlaps` would match if the two sets are disjoint)
* matching on bool values with == or !=
* appending to a list value, or force-appending, which appends to lists normally, coerces non-lists into lists with one element and initializes nonexisting lists
* unit tests for all of …
=> ENH: Refactor some of the Sieve expert, extend the Sieve DSL

intelmq/lib/mixins/http.py
=> BUG: http mixin: fix http_password setting auth

NEWS.md, docs/dev/data-format.rst, intelmq/bots/experts/idea/expert.py, intelmq/bots/experts/taxonomy/expert.py, intelmq/bots/parsers/github_feed/parser.py, intelmq/lib/harmonization.py, intelmq/tests/bots/parsers/github_feed/test_parser.py
ENH: harmonization: create and use other/malware
the classification
malicious code / malware
is replaced by
malcious code / infected system
malcious code / malware-distribution
other / malware for all other cases, i.e. malware itself
fixes #1752
related to #1409
DOC: fixes for "other" classification
=> Introduce Other/malware classification

intelmq/bin/intelmqctl.py
Adding list bots output in intelmqctl for better user experience.
It will show all available bots and in which category they are.
Fixes #1924
=> ENH: Add intelmq list bots output

.github/workflows/docker.yml
Publishing a new docker image to certat/* namespace on dockerhub
will only run if repository name is certtools/intelmq. So forks
dont fail as they dont execute the publish commands.
Fixes #1931
=> FIX: GHA docker workflow publish

intelmq/bots/experts/rdap/expert.py
If status code not in 2xx range, then we throw an error to get administrators attention. There might be an configuration problem or smth else. Status-Code 404 is special, data will not get enriched as rdap does not have any information about that given domain.
Fixes #1887 
Fixes #1893
=> FIX: intelmq.bots.experts.rdap evaluates http status codes

CHANGELOG.md, docs/user/bots.rst
DOC: Bots: sections for common parameters, can be linked then
DOC: bots documentation: fix sections
removes duplicate fireeye section
merges duplicate/obsolete mcaffee expert sections
adds missing information block for csv parser
DOC: bots: add anchors for all sections
adds the module name of bots as section anchor
adds the module name to the information block if it was missing or
incomplete
fixes part of certtools/intelmq-api#4
counterpart is https://github.com/certtools/intelmq-manager/pull/256
=> Bots documentation: add anchors to all sections

docs/user/bots.rst, intelmq/bots/experts/sieve/expert.py, intelmq/bots/experts/sieve/sieve.tx, intelmq/tests/bots/experts/sieve/test_expert.py, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_equals_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_overlaps_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_setequals_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_subsetof_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_list_supersetof_match.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_mixed_if.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_negation.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_nested_if.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_typed_values.sieve
This PR has three parts:
* generic negation of arbitrary expressions, along with the removal of the list match negation
* nested if statements, plus mixed actions and actions in the same scope
* the attribute manipulation actions `add`, `add!` and `update` support non-string (bool/int/float) values
There is also an RFC-ish last commit, with some somewhat breaking changes.
* Some operators which were made redundant by negation (`!~` and `:notcontains`) are removed
* `:in` is used for list inclusion checks instead of `==`
* there's a clear split between single-value and multi-value matches, with a couple of new operators due to that: `:containsany` and `:regexin` for string matching against multiple regexes or string inclusions)
The last commit is not expected to be accepted at the moment. …
=> Sieve: expression negation, nested if / mixed conditionals and actions, support for non-strings in add/add!/update

intelmq/bots/experts/rdap/expert.py, intelmq/tests/bots/experts/rdap/test_data/example.com.json, intelmq/tests/bots/experts/rdap/test_data/nic.versicherung.json, intelmq/tests/bots/experts/rdap/test_data/rdns.json, intelmq/tests/bots/experts/rdap/test_expert.py, setup.cfg
As some RDAP implementation may vary, we check if the entity
is a valid entity-type. As of the RFC for RDAP only JSON dicts
are allowed.
Closes #1942
=> FIX: RDAP checks if entity is valid entity-type

docs/dev/release-procedure.rst, docs/user/installation.rst, docs/user/upgrade.rst
Adapted docker instructions as they are now a bit different than
our first release. We are publishing intelmq with its current
version on dockerhub now. Tag 1.0 will remain but is deprecated.
=> DOCS: Updated docker instructions

docs/user/intelmqctl.rst
To make the `intelmqctl run` subcommands more clearly subcommands and
make them subsections of the `intelmqct run` section, the sections had
to be raised in the whole document.
Closes #1936
=> DOC: Rearrange section levels

CHANGELOG.md, intelmq/bots/outputs/smtp/output.py, intelmq/lib/bot_debugger.py
ENH: lib/bot_debugger: better detect bot type for message type
Do not rely on the runtime configuration's `group` setting of bots to determine the required message type of messages given on the command line
ENH: smtp output: Add more debug logging
=> Minor enhancements to bot debugger and SMTP output

intelmq/bin/intelmqctl.py
The log subcommand only works on configured bots, so the bot_id should
be one of specific set of choices.
Closes #1935
=> FIX: set the choices for the intelmqctl log subcommand

NEWS.md, docs/user/bots.rst, intelmq/bots/experts/sieve/expert.py, intelmq/bots/experts/sieve/sieve.tx, intelmq/tests/bots/experts/sieve/test_expert.py, intelmq/tests/bots/experts/sieve/test_sieve_files/test_keep_event.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_numeric_match_value_list.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_string_match_value_list.sieve, intelmq/tests/bots/experts/sieve/test_sieve_files/test_string_notcontains_match.sieve
This commit:
* drops the `:notcontains` and `!~` from Sieve, as they are made redundant by negation (`! foo :contains 'x'` == `foo :notcontains 'x'`)
* splits string and numeric matches into single- and multivalued variants, with the relevant new operators `:in`, `:containsany` and `:regexin` for string lists, and `:in` for numeric value lists
* adds documentation and tests for the above
* adds a note to the documentation regarding breaking changes
Should the breaking changes be referenced somewhere besides the documentation as well?
=> ENH: Sieve: Drop redundant operators, split string and numeric matches into single- and multivalued variants

intelmq/bots/experts/splunk_saved_search/expert.py
Move the entire expression out of the f-string into the argument to `str.format()`, fixing the "KeyError: 'field'" that has been the only
result of running this bot since commit ddc213021775828a535b5ef88f9b4224a2161f7f (BUG/TST: fix splunk expert on python 3.5).
This bug is also present in the `develop` branch. Do you want to cherry-pick this commit to there, have me submit another pull request, revert ddc213021775828a535b5ef88f9b4224a2161f7f on that branch, or something else?
=> Correct fix of Splunk expert on Python 3.5

.github/pull_request_template.md, CHANGELOG.md, NEWS.md, SECURITY.md, docs/README.md
=> FIX: change copyright header syntax in md files

intelmq/lib/test.py
The `output` field in the harmonization is defined as a ["unicode string[] with JSON objects"](https://github.com/certtools/intelmq/blob/06d70e3ba82f80074492a05a049f61a91bb40115/intelmq/lib/harmonization.py#L905). [lib.test.BotTestCase.assertMessageEqual()](https://github.com/certtools/intelmq/blob/06d70e3ba82f80074492a05a049f61a91bb40115/intelmq/lib/test.py#L516) does not special-case the `output` field (as it does with `time.observation`), leading it to be treated as a string and compared according to string equivalence. However, according to [the JSON spec](https://www.json.org/json-en.html), "[a]n object is an unordered set of name/value pairs".
This leads to two objects differing only in the order of their fields when serialized comparing as different according to IntelMQ, when they …
=> Compare "output" fields as JSON objects, not strings

intelmq/lib/utils.py
copy2 tries to copy file attributes. This leads to problems when we try
to use the write_configuration function from code that runs under
another user, even when the user is in the intelmq group.
Simple copying the content of the file should be enough, though.
=> ENH: replace copy2 with pathlib

CHANGELOG.md, intelmq/lib/bot.py, intelmq/lib/pipeline.py, intelmq/lib/test.py
allows bots accessing data directly on startup/initialization for cleanup or maintenance tasks
this required small adaptions in the test code, and shortens its code a
bit
related: certtools/intelmq#1968
related: certtools/intelmq#1959
@waldbauer-certat  please verify if this solves your issue
=> ENH: lib/bot: Init pipeline before init call

CHANGELOG.md, NEWS.md, docs/dev/data-format.rst, intelmq/bots/experts/idea/expert.py, intelmq/bots/experts/taxonomy/expert.py, intelmq/bots/parsers/bambenek/parser.py, intelmq/lib/harmonization.py, intelmq/tests/bots/parsers/bambenek/test_parser.py, intelmq/tests/lib/test_harmonization.py
move "dga domain" to the taxonomy other, as it is not accepted in RSIT
rename to "dga-domain" to match the name scheme of other types
adapt bots depending on the name
add changelog and news entries, including SQL update statements
=> harm: move dga domain classification to other

intelmq/lib/pipeline.py, intelmq/lib/utils.py
Ruamel YAML defaults to the rt (round-trip) loader, which preservs
comments.
=> FIX: Use the default loader of ruamel yaml

intelmq/bots/collectors/api/collector_api.py
The first commit adds the option of using UNIX sockets instead of TCP sockets for the API collector, which has performance benefits, and the second fixes an issue with the collector if the collector is reloaded.
=> API collector: Optionally use UNIX sockets instead of TCP sockets, fix #1986

AUTHORS, docs/user/bots.rst, intelmq/bots/outputs/templated_smtp/REQUIREMENTS.txt, intelmq/bots/outputs/templated_smtp/output.py, intelmq/tests/bots/outputs/templated_smtp/test_output.py
The current SMTP output bot only supports formatting events as CSV attachments, which is not flexible enough for our needs, which include sending JSON-formatted attachments. Hence, this bot, which dumps the responsibility for formatting onto the runtime configuration, allowing you to create things like:
```yaml
attachments:
- content-type: application/json
text: |
{{
"host": "{event[source.fqdn]}",
"malware": "{event[malware.name]}"
}}
name: report.json
```
Available formatting is limited to string substitution. This was sufficient for our needs, and avoids introducing control structures in the templates. If you feel there is a need for even more complicated output formatting, I could look into integrating a full template engine, e.g. Jinja.
The code and tests are heavily based on the …
=> Add templated SMTP output bot

intelmq/lib/pipeline.py, intelmq/tests/lib/test_pipeline.py
the arguments given by pipeline_args were not effective, as the
load_configuration methods of the pipeline classes still tried to access
the parameters at self.
also modify the tests to catch a bug like this in the future
fixes certtools/intelmq#1875
=> BUG: lib/pipeline: fix argument uptake

intelmq/bots/collectors/shodan/collector_stream.py
The `error_max_retries` attribute is no longer accessed via `self.parameters` and the Shodan collector appears to have been missed in the updates.
=> FIX: s/self.parameters/self/ in Shodan collector

intelmq/bots/collectors/mail/collector_mail_attach.py
=> BUG: provide filename when reading a non-archived file from mail

docs/dev/feeds-wishlist.rst, docs/user/installation.rst
@wagner-certat
DOC: dev/feeds whishlist: add two potential feeds
0c5c400
@wagner-certat
DOC: install: note on leap 15.3
9fef258
falcon and hug are in backports, both are required for the API
=> Docs: 2 new entries for feeds whishlist, small note in install docs regarding openSUSE leap 15.3

intelmq/lib/bot_debugger.py, intelmq/lib/pipeline.py
This PR fixes two issues:
* `bot_debugger` attempts to access a bot's private `destination_queues` attribute, despite it being public now
* changes in the passing of pipeline parameters made the `load_balance` parameter not work
=> Core fixes

CHANGELOG.md
=> DOC: Fix typo

intelmq/bots/experts/asn_lookup/expert.py, intelmq/bots/experts/domain_suffix/expert.py, intelmq/bots/experts/maxmind_geoip/expert.py, intelmq/bots/experts/recordedfuture_iprisk/expert.py, intelmq/bots/experts/tor_nodes/expert.py
This introduces a --verbose flag to the experts which use update
functions. The default behaviour now is to *not* print any messages,
which makes the update function less noisy when used with cron.
Fixes #2016
In the long run we should probably move the update logic to the bot class itself.
=> Make update script less verbose by default

setup.cfg
Exclude .cover, that's where the HTML report of code coverage is placed
and this can be ignored
remove the exclusion of name "ether", it's nowhere in the code anyway
=> codespell: Exclude coverage output

docs/user/configuration-management.rst
=> DOC: remove mention of intelmqctl list bot json output

intelmq/lib/bot.py
XMPP based bots were removed in 3.0.0
=> Remove workarounds for XMPP bots

intelmq/lib/pipeline.py, intelmq/lib/utils.py
This lets us be backwards compatible to JSON and still dump YAML in a
readable format.
Another approach would be to first try to load JSON and only if that fails use yaml with the default loader.
=> Use the YAML unsafe loader instead of the safe loader

CHANGELOG.md, intelmq/lib/bot.py
the manager (or any user in the file directly) sets destination_queues
to an empty dict. the check `is not None` did not catch empty dicts,
initializing the destination pipeline even when no queues were defined.
The check is now more lax and the code handles empty dicts normally,
making them also the default value instead of None.
fixes certtools/intelmq#2034
@monoidic please check if that solves your observed error
=> BUG: lib/bot: handle empty dict in destination_queues

CHANGELOG.md, intelmq/bots/outputs/smtp/output.py, intelmq/tests/bots/outputs/smtp/test_output.py
fixes display of the attachment in mail clients
fixes certtools/intelmq#2018
=> BUG: smtp output: add Content-Disposition header for attachments

intelmq/lib/bot.py
that way we can exclude it from attribute listings of the bots
attributes.
=> Make the harmonization attribute of the bot private

CHANGELOG.md, intelmq/bots/collectors/mail/_lib.py
use existing standard http_verify_cert parameter to determine if
certificate should be checked or not.
default (backwards-compatible) is to verify the server certificate
cc @th-certbund
=> ENH: imap collector: support unverified connections

intelmq/lib/utils.py
some bots' doc string contain newlines at the beginning or the end of
the string depending on how the comment is formatted. These newlines are
just confusing in the UI, so remove them.
=> ENH: utils: list_bots: strip descriptions

intelmq/lib/harmonization.py
change type from list to tuple, this list is immutable
sort
remove duplicate value system-compromise
=> lib/harm: minor change to allowed classification.types list

CHANGELOG.md, docs/user/upgrade.rst, intelmq/bin/intelmqctl.py, intelmq/lib/upgrades.py, intelmq/tests/lib/test_upgrades.py
merge defaults and runtime configuration, only using the new format with
the global parameters
add **kwargs to the upgrade functions to allow adding more paramters
without breaking the old functions
handle the global parameters in all functions and update the tests
accordingly
Independent of this change, config-upgrade issues may appear in regards
to the defaults config file if intelmq versions are skipped.
pass `version_history` to functions
this allows the upgrade functions to determine if this is a new
installation or an upgraded intelmq instance
=> ENH: small refactor of upgrade functions

docs/user/bots.rst, intelmq/bots/experts/jinja/expert.py, intelmq/tests/bots/experts/jinja/ecs.j2, intelmq/tests/bots/experts/jinja/ecs.j2.license, intelmq/tests/bots/experts/jinja/test_expert.py
This commit adds a simple jinja expert bot, that lets you modify message
data using jinja2 templates.
It add the relevant documentation to the bots file and also a couple of
unit tests.
=> JinjaExpert - modify message fields using jinja2

docs/user/configuration-management.rst
the parameter `broker` is deprecated
enhance description of source/destination_pipeline_broker:
- use link syntax
- add amqp
- add note on usefulness
=> DOC: configuration: fix broker description

CHANGELOG.md, intelmq/bots/experts/filter/expert.py, intelmq/tests/bots/experts/filter/test_empty_string_parameters.py
if any of these two parameters contained empty strings, the bot
initialization failed
fixes certtools/intelmq#2074
=> BUG: filter: handle empty string not_after & not_before

CHANGELOG.md, intelmq/bin/intelmqctl.py, intelmq/lib/datatypes.py, intelmq/lib/processmanager.py
This commit introduces a separate module for the processmanagers. The
module also contains a processmanager interface all the processmanager
should adhere to.
=> Refactoring intelmqctl

CHANGELOG.md, intelmq/lib/bot.py
Add `enabled` and `run_mode` as members of the `Bot` class with default values.
Log the system parameters in the same way as default and runtime parameters.
Warn if disallowed system parameters are encountered.
Warn if no configuration could be found in the runtime configuration file for the bot's ID.
Re-initialize logging if logging parameters have been changed by environment variables.
=> ENH: lib/bot: fix behavior for unconfigured bots

CHANGELOG.md, intelmq/bin/intelmqctl.py
the global block of the runtime configuration was not excluded in one
block, raising an exception
fixes certtools/intelmq#2085
=> ctl: fix managment of bot groups

intelmq/bin/intelmqctl.py
=> BUG: use correct private parameter variable

docs/dev/guide.rst, docs/user/intelmq-manager.rst, intelmq/bin/intelmqctl.py, intelmq/bots/collectors/http/collector_http.py, intelmq/bots/collectors/http/collector_http_stream.py, intelmq/bots/collectors/misp/collector.py, intelmq/bots/collectors/shadowserver/collector_reports_api.py, intelmq/bots/experts/http/expert_status.py, intelmq/bots/experts/jinja/expert.py, intelmq/bots/experts/splunk_saved_search/expert.py, intelmq/bots/experts/tuency/expert.py, intelmq/bots/outputs/elasticsearch/output.py, intelmq/bots/outputs/misp/output_api.py, intelmq/bots/parsers/hibp/parser_callback.py, intelmq/bots/parsers/mcafee/parser_atd.py, intelmq/bots/parsers/microsoft/parser_ctip.py, intelmq/bots/parsers/shadowserver/parser_json.py, intelmq/bots/parsers/twitter/parser.py, intelmq/etc/feeds.yaml, intelmq/lib/bot.py, intelmq/lib/exceptions.py, intelmq/lib/message.py, intelmq/lib/mixins/sql.py, intelmq/lib/pipeline.py
This commit fixes various errors and warnings from sphinx, mostly due to
wrong indents.
=> DOCS: fix some sphinx warnings

CHANGELOG.md, intelmq/bin/intelmqctl.py
the default logging path is not opt, it's the constant from the top
`__init__.py`, which is different for deb/rpm packages
fixes certtools/intelmq#2091
=> BUG: ctl: fix default logging path

.github/workflows/ansible-tests.yml, .github/workflows/scripts/ansible-playbook.yml
This makes the ansible workflow follow the upstream playbook more
closely, which reduces duplicate code.
=> ENH: use the upstream ansible tasks playbook

docs/user/installation.rst
Updated docker installation instructions to work with the latest pushes to the intelmq-docker repository.
In addition added the explanation how to set a custom username and password to the intelmq api inside the docker container.
=> DOCS: Updated docker installation instructions

docs/user/bots.rst, intelmq/bots/outputs/rpz_file/output.py, intelmq/tests/bots/outputs/rpz_file/test_output.py
**Add new bot: RPZ file output**
Example output file:
```
$TTL 3600
@ SOA rpz.yourdomain.eu. hostmaster.rpz.yourdomain.eu. 2105260601 60 60 432000 60
NS localhost.
;
; yourdomain.eu. CERT.XX Response Policy Zones (RPZ)
; Last updated: 2021-05-26 06:01:41 (UTC)
;
; Terms Of Use: https://rpz.yourdomain.eu
; For questions please contact rpz [at] yourdomain.eu
;
*.maliciousdomain.com CNAME rpz.yourdomain.eu.
*.secondmaliciousdomain.com CNAME rpz.yourdomain.eu.
```
=> Add RPZ file output bot

docs/user/bots.rst, intelmq/bots/outputs/bro_file/output.py, intelmq/tests/bots/outputs/bro_file/test_output.py
=> Add new bot: bro  output file

docs/user/bots.rst, intelmq/bots/experts/cut_from_string/expert.py, intelmq/bots/experts/remove_affix/expert.py, intelmq/tests/bots/experts/cut_from_string/test_expert.py, intelmq/tests/bots/experts/remove_affix/test_expert.py
Add new bot: cut string from string
=> Add new bot: cut string from string
